### ISSUE TITLE
Add support for Matplotlib's perceptually uniform colormaps

### ISSUE THREAD

**Issue by tzanio** [GLVis/glvis#100]
It may be nice to add the perceptually uniform colormaps `viridis`, `plasma`, `inferno`, `magma`, `cividis` from Matplotlib.

More information here: https://matplotlib.org/tutorials/colors/colormaps.html.

Here is a nice video explaining their design: https://youtu.be/xAoljeRJ3lU.

**Comment by v-dobrev** [comment]
"Turbo" is another nice palette: https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html. Direct link to the palette definition in C: https://gist.github.com/mikhailov-work/6a308c20e494d9e0ccc29036b28faa7a.

**Comment by pazner** [comment]
+1 for the Turbo color map.

I have some code that will generate a Turbo colormap for GLVis (also VisIt and ParaView): https://github.com/pazner/turbo_colormaps

Running `python glvis.py` should output C++ code that can be copied-and-pasted into GLVis.

**Comment by tzanio** [comment]
I am working on this

**Comment by tzanio** [comment]
For the record, here are a few other relevant sites
- [Visualizing Science: How Color Determines What We See](https://eos.org/features/visualizing-science-how-color-determines-what-we-see)
- [CMasher: Scientific colormaps for making accessible, informative and cmashing plots](https://github.com/1313e/CMasher)
