### ISSUE TITLE
Showing log plot of data controlled by value range

### ISSUE THREAD

**Issue by homijan** [GLVis/glvis#104]
Hi GLVis,

could I get an advice about plotting data in logarithmic scale?
I have difficulties plotting a "steep" solution (keys iii) in log scale (keys L), because I get negative values after refining. My original data is within the range (0, 1.0).
I tried to use valuerange as following
{  
  autoscale off
  valuerange 0.00001 1.0
  keys iii
  keys L
}
but the range I am seeing is strange.
Is it correct to expect the Log range of the above to be (-5, 0)?

Thanks!

**Comment by tzanio** [comment]
Does the following work for you:

- Press `F7` and set the min value to 0.00001
- Press `L`

Tzanio

**Comment by v-dobrev** [comment]
The values (-5,0) correspond to log_10 of the value range (1-e5,1). Where do you see the values (-5,0)? On the colorbar, or on the bounding box? Also, is this 2D or 3D?
