### ISSUE TITLE
Visualizing mfem ex15 causes error

### ISSUE THREAD

**Issue by termi-official** [GLVis/glvis#105]
Hi,

running ex15 (and ex15p) with small meshes causes random errors in GLVis. I built both from source from their corresponding master, but it is also present in all mfem branches which I tested.
For example
```
examples/ex15 -m ../data/amr-quad.mesh
```

gives me in ex15 the error message `Error in send(): Broken pipe` after 42 timeseps.
And in glvis `Stream: end of input.` where the following break was taken
https://github.com/GLVis/glvis/blob/3422dbad8137dda588e842b90396d35fa05ec1f6/lib/threads.cpp#L859-L863

For me this is also reproducible for other small meshes like the provided Fichera mesh. Maybe this one could be best for debugging because it may trigger the problem quicker (first timestep for me). 

Best regards,
Dennis

**Comment by rw-anderson** [comment]
I tried this with the latest master of both glvis and mfem and could not reproduce it.  The run finishes without errors for me.  Same with the fichera mesh.  I'm on an Ubuntu desktop using g++.

**Comment by termi-official** [comment]
My test system has opensuse + clang8 build from source. The problem present in Debug and Release builds. 
I will try to pin this down further (+gcc build) in a few days.

**Comment by tzanio** [comment]
This is difficult to reproduce and could be due to a variety of reasons.
