### ISSUE TITLE
Are the "cutting plane" and "clipping plane" the same thing?

### ISSUE THREAD

**Issue by rw-anderson** [GLVis/glvis#107]
The 3D docs reference a "cutting plane" and a "clipping plane".  Are these the same thing?  If so, probably one word should be chosen and made consistent.

![help](https://user-images.githubusercontent.com/11507994/90593675-5cb98a80-e19d-11ea-917d-8f9bbf074d15.png)

**Comment by tzanio** [comment]
Yes they are, and yes we should fix that :)

I personally have a slight preference for "cutting" than "clipping", but both can work.

**Comment by v-dobrev** [comment]
The term "clipping plane" comes from OpenGL, e.g. the function `glClipPlane(...)`, the flag `GL_CLIP_PLANE0`, etc.

In the context of GLVis though, "cutting plane" makes sense too. I'm fine with either choice, if you want to unify the terminology.

**Comment by tzanio** [comment]
@rw-anderson do you want to propose a simple PR for this?

**Comment by tzanio** [comment]
Addressed in https://github.com/GLVis/glvis/pull/123/commits/49bc42c7e12b1859bc7f14acb1207c1472671df0 as part of the `v4.0-dev` branch
