### ISSUE TITLE
Segmentation fault when visualizing GMSH mesh file

### ISSUE THREAD

**Issue by jediyoda36** [GLVis/glvis#108]
Hi,

I just wrote a simple mesh file by using GMSH api, the msh file works fine in MFEM. But when I trying to visualizing it in GLVIS, it occurs a segmentation fault.

![image](https://user-images.githubusercontent.com/13287220/93549532-16259e80-f99c-11ea-893d-a5ef4b708b07.png)

Is there any solution for this problem?
My mesh file is attached.(Github doesn't support the msh file, please change the file type to .msh)
[Hole.txt](https://github.com/GLVis/glvis/files/5243059/Hole.txt)

**Comment by tzanio** [comment]
@jandrej, @sshiraiwa or @bslazarov, can you take a look?

**Comment by mlstowell** [comment]
Hi, @jediyoda36 ,

Unfortunately, this mesh is not supported by MFEM.  If I'm reading it correctly, the mesh starts with 702 line segment elements followed by thousands of triangles.  By my count 520 of these line segments are not edges of any of the triangles. For example, if you search for node number 584 it occurs in two of the line segments but none of the triangles.

It would seem that this mesh has a large 2D region meshed with triangles and one or more 1D regions meshed with line segments.  MFEM does not support such meshes.  When MFEM reads a mesh it assumes the domain has a dimension equal to the dimension of the highest dimension element (2D in this case).  MFEM then makes the further assumption that any elements which are one dimension less will form the boundary of the mesh.

Best wishes,
Mark

**Comment by jediyoda36** [comment]
@mlstowell thanks for the reply :)

I'm using gmsh to create a mesh with holes, the gmsh output just like I attached in this issue.  If this mesh doesn't supported by MFEM, do you have any other suggestion about mesh generator? 

Currently, my requirements are: 
- Input nodes and define lines, surfaces, boundary attributes
- Able to generate triangle meshes
- Able to generate meshes with holes
- Optional: C++ or Python api
- Optional: CAD file input

**Comment by sshiraiwa** [comment]
@jediyoda36, what Mark is indicating is that your mesh is not suitable to define the finite element problem. In MFEM, the entire domain needs to be connected, and the boundary (edges for 2D, faces for 3D) is also connected with the domain. In other words, the line needs to be an edge of triangles. 
Looking at your mesh file below, the three group of edges (yellow and blue) are separate elements, not connected with triangles. (By the way, this doesn't seem like a hole. Maybe I misunderstood what you mean by hole)
![Screenshot_2020-09-27_01-06-17](https://user-images.githubusercontent.com/1929159/94356522-ac715880-005d-11eb-9519-092b0b31072e.png)

Regarding a tool, GMSH is totally fine. in fact we are using it for meshing rather complicated structures with GMSH and MFEM is happy with it. (Some example below., here, I used GMSH python API and PythonOCC to handle CAD data.)
![Screenshot_2020-09-27_01-02-39](https://user-images.githubusercontent.com/1929159/94356481-29500280-005d-11eb-8397-3400d1ab8665.png)

**Comment by mlstowell** [comment]
Hi, @jediyoda36 ,

Most of us are not Gmsh experts but if you post a Gmsh script that can generate your geometry we might be able to offer more specific advice.  It sounds like Gmsh and MFEM should be capable of creating and reading a mesh satisfying your requirements and I'd be happy to help if I can.

Best wishes,
Mark

**Comment by jediyoda36** [comment]
@mlstowell @sshiraiwa thanks for the reply!

I think I use GMSH in a wrong way, I'll try it again. If there is any other question, I'll post here.

**Comment by bslazarov** [comment]
Hi Tianchen,

Perhaps the easiest way is to upload a sample of your geo (gmsh) input
file. Then we can help you with the options and how to generate a good mesh
input for MFEM.

**Comment by jediyoda36** [comment]
Hi @bslazarov, thanks for the reply.

Currently my team is using MFEM to simulating circuit parameters. The original input file is not .geo file. I'm using other Python package to read the input then meshing it with GMSH Python api.
I'll upload an example .geo file which has the same shape with the original input in next week.

**Comment by sshiraiwa** [comment]
If you prefer, we can help you with your python script to use GMSH, too.
This may be simply the matter of shape embedding before meshing.

**Comment by jediyoda36** [comment]
@sshiraiwa Thanks for helping! I need to ask my boss if I can upload the python script to github. 
For now, the problem is solved (I think). If there is any other similar problem, I'll post the problem here.

@tzanio @bslazarov @mlstowell You guys helped a lot, thanks!

p.s there is another issue about using `navier_3dfoc.cpp`, I'll post it in MFEM repo later.

**Comment by jediyoda36** [comment]
Hi Mr. Shiraiwa @sshiraiwa ,
I have a follow up question about dealing with CAD data.

I created a brep file by using PythonOCC.
![image](https://user-images.githubusercontent.com/13287220/103718327-76028c80-5001-11eb-8f43-4a94bd77db01.png)

In this case, I need to add 4 different boundary attributes in this brep file.
![image](https://user-images.githubusercontent.com/13287220/103718363-89adf300-5001-11eb-8123-0196406ac8d9.png)

So, what’s your workflow to handle CAD data? And how do you add boundary attribute with PythonOCC or GMSH API?

Here is my brep file. (GitHub doesn't support brep file, please change file type to brep)
[CalcArea.txt](https://github.com/GLVis/glvis/files/5773441/CalcArea.txt)

**Comment by bslazarov** [comment]
Hi, 

We do not work directly with CAD data. MFEM reads only mesh files. The easiest way to add boundary attributes/mark the faces is to open the CAD file in gmsh and use the graphical interface to see the face numbers. Once you know their numbers you can define physical surfaces - these will be exported in the output mesh with the assigned marks.

**Comment by jediyoda36** [comment]
@bslazarov thanks for the reply!

> The easiest way to add boundary attributes/mark the faces is to open the CAD file in gmsh and use the graphical interface to see the face numbers. Once you know their numbers you can define physical surfaces - these will be exported in the output mesh with the assigned marks.

That's what we are doing now.  But for some reason, we want to use Python to handle our CAD data,  just like Mr. Shiraiwa @sshiraiwa mentioned above.

By the way, what GMSH version are you using? Does MFEM support GMSH 4 format now?

**Comment by bslazarov** [comment]
MFEM support only version 2.x for GMSH input.
