### ISSUE TITLE
Apply more than one grid function to a mesh

### ISSUE THREAD

**Issue by jediyoda36** [GLVis/glvis#114]
Hi, I'm currently using `tesla.cpp` mini-app. Is there any way to apply two grid functions (`* h_` and `* j_`) on one mesh (square-angled-pipe) in the same time? We are trying to compare magnetic Field and volumetric current density .

**Comment by tzanio** [comment]
Sorry, you can't visualize two functions on the same mesh.

One option is to pre-process them in your application, and maybe save the difference and visualize that?

**Comment by pazner** [comment]
This kind of visualization should also be possible to do by saving both grid functions in a data collection, and using e.g. VisIt or ParaView.

**Comment by jediyoda36** [comment]
> This kind of visualization should also be possible to do by saving both grid functions in a data collection, and using e.g. VisIt or ParaView.

Thanks! I'll try it out.

**Comment by pazner** [comment]
> > This kind of visualization should also be possible to do by saving both grid functions in a data collection, and using e.g. VisIt or ParaView.
> 
> Thanks! I'll try it out.

I should have mentioned — you can look at MFEM's example 5 for an example of saving two grid functions in one data collection (both VisIt and ParaView formats).
