### ISSUE TITLE
Problem with XQuartz when running Tesla mini-app

### ISSUE THREAD

**Issue by jediyoda36** [GLVis/glvis#118]
Hi,

I'm currently using Tesla mini-app. When I'm running `mpirun -np 4 ./tesla -m square-angled-pipe.mesh -kbcs '3' -vbcs '1 2' -vbcv '-0.5 0.5'` on a Ubuntu machine through ssh connection, it works fine, several Glvis windows showed and stayed on my screen. 

However, when I'm running same command on my mac (through ssh connection as well), the Glvis windows (or to say XQuartz windows? ) just pop-up and then disappeared quickly.

Is there any way to fix this problem?

**Comment by v-dobrev** [comment]
This sounds like an issue between the remote x-client (running on the remote Mac) and the local x-server. Did you get any error messages in the terminal where you ran GLVis?

To avoid such incompatibilities between x-client and x-server, you can try this: build and run GLVis locally and then when you ssh to a remove machine to run the miniapp there, use port forwarding to forward the GLVis port (the default port is 19916) from the remote machine to the local machine. The command will be something like:
```console
ssh user@server -R 19916:localhost:19916
```

**Comment by jediyoda36** [comment]
@v-dobrev thanks for the reply!

I tried to run glvis locally, but it didn't fix this problem.

> Did you get any error messages in the terminal where you ran GLVis?

There is no error message.

![image](https://user-images.githubusercontent.com/13287220/100687510-6917cb00-33bb-11eb-829d-025683a08ab9.png)

When I was running other mini-apps or examples, there is no such problem. I think the main reason is Tesla mini-app output multiple graphs at one time.

**Comment by tzanio** [comment]
What happens if you run `ex5` -- do you see two windows ("Velocity" and "Pressure")?

**Comment by jediyoda36** [comment]
@tzanio yes, there are two windows.

**Comment by jediyoda36** [comment]
@tzanio And I also run the ex5p, it works fine.

**Comment by tzanio** [comment]
I wonder if it is something in `VisualizeField` in `miniapps/common`... this is supposed to be a more robust way to open multiple GLVis windows than the simple one used in Example 5, 10, etc.

Can you try `miniapps/tools/display-basis.cpp` -- does this open multiple GLVis windows for you?

**Comment by jediyoda36** [comment]
@tzanio Yes it does.
![image](https://user-images.githubusercontent.com/13287220/100699938-367bcb80-33d7-11eb-96e5-0cfe8f1737aa.png)

**Comment by jediyoda36** [comment]
@tzanio I tried again to run Tesla mini-app, this time there is only one window remain.
![image](https://user-images.githubusercontent.com/13287220/100700371-3c25e100-33d8-11eb-9d97-3c11ceea2a55.png)

**Comment by v-dobrev** [comment]
Can you try building GLVis in debug mode: if you are using `make` just add `GLVIS_DEBUG=YES` to the build command line; if using `cmake`, add `-DCMAKE_BUILD_TYPE=Debug`. This should make GLVis print some additional messages. Can you post the output from the failing Tesla run? The output from the different windows will be mixed up but it still may give us some clue.

Also, just to make sure: are you using the latest release versions of MFEM and GLVis, the latest `master` branches from GitHub, or some older versions / commits?

**Comment by jediyoda36** [comment]
@v-dobrev There are some errors when I built glvis in debug mode
![image](https://user-images.githubusercontent.com/13287220/100980065-a5942400-357f-11eb-9ce1-a166f73531e5.png)

**Comment by jediyoda36** [comment]
@tzanio @v-dobrev 
I reinstalled mfem and glvis in latest version (master branch on github), problem solved.
Thanks for helping!
