### ISSUE TITLE
undefined reference to `gluPerspective'

### ISSUE THREAD

**Issue by miaodi** [GLVis/glvis#119]
Hi,
I am compiling glvis in Ubuntu 20.04. I got the following error message:

/usr/bin/ld: lib/libglvis.a(aux_vis.cpp.o): in function `MyReshape(int, int)':
aux_vis.cpp:(.text+0x2a2e): undefined reference to `gluPerspective'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/glvis-exe.dir/build.make:90: glvis] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/glvis-exe.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

How could I fix it?

Regards,
Di

**Comment by v-dobrev** [comment]
It looks like you are missing one of the dependencies: GLU. Try installing the package `libglu1-mesa-dev`, see https://packages.ubuntu.com/focal/libglu1-mesa-dev.

**Comment by tzanio** [comment]
@miaodi, were you able to resolve this?

**Comment by kanye-quest** [comment]
Closing as glvis no longer depends on GLU. If you encounter any other issues with building and/or dependencies, feel free to make a new issue.
