### ISSUE TITLE
Building issue with MFEM built with MPI support on Linux

### ISSUE THREAD

**Issue by v-dobrev** [GLVis/glvis#120]
This issue with X11 and MPI was reported here: https://github.com/GLVis/glvis/pull/66#issuecomment-738282716 and unfortunately was not fully resolved by 8fe6bdd. We still have `sdl.cpp` includes `threads.hpp` which includes `mfem.hpp` which includes `mpi.h` (when MFEM is built with MPI). On the other hand `sdl.cpp` also includes `sdl_x11.hpp` --> `X11/extensions/XInput2.h` --> `X11/Xlib.h`.

cc: @termi-official, @kanye-quest, @tzanio

**Comment by kanye-quest** [comment]
Related: https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/15

IMO, I think we should just `#undef Status` after including the X11 headers - it's just being used as an alias for int.

**Comment by v-dobrev** [comment]
> IMO, I think we should just `#undef Status` after including the X11 headers - it's just being used as an alias for int.

@kanye-quest, sounds fine to me. Do you want to make a branch to fix this?
