### ISSUE TITLE
Add CI testing with GitHub Actions

### ISSUE THREAD

**Issue by tzanio** [GLVis/glvis#124]
We should add smoke test for

- building on Linux, Mac
- code styling
- ...

**Comment by tzanio** [comment]
It will be great if we test the actual usage, e.g. compare screenshots of pre-defined datasets as a form of regression testing.

**Comment by tzanio** [comment]
We should also test the glvis-js and pyglvis repos

**Comment by tzanio** [comment]
I think we can close this after #176 is merged. Do you agree @adrienbernede?

**Comment by adrienbernede** [comment]
I agree! Awesome leap forward!

**Comment by tzanio** [comment]
Discussion continued in #176
