### ISSUE TITLE
Save a snapshot after transformation in a command line

### ISSUE THREAD

**Issue by martemyev** [GLVis/glvis#13]
Dear All,

I'm trying to save a snapshot after transforming it to 2D view using the following command:
```bash
glvis -m mesh -g solution -k RjlkaSq
```
i.e. I set 2D (R), turn off perspective (j), turn off light (l), make it slightly transparent to see the left bottom coordinate (k), display axis (a), then I want to save the resulting view as a snapshot (S), and exit (q). However, GLVis saves the snapshot at an earlier stage in 3D (I guess before all the transformations happen). 

I know I can save the desirable snapshot when GLVis window is open, but I'd like to execute this command in a script.

Any suggestion would be highly appreciated!

Thanks,
Mikhail

**Comment by v-dobrev** [comment]
Hi Mikhaill,

Some keys specified on the command line are processed in such a way that they take effect later: a key may cause an event (e.g. a redraw) that is put at the end of the X events queue, i.e. after all specified keys.

For the purpose of creating sequences of GLVis screenshots we use GLVis scripts, as described [here](http://glvis.org/options-and-use/#glvis-scripts).

Here is another example:

```
# window position and size
window 0 0 800 800

# load initial mesh and solution
solution mesh.00 solution.00

# this section adjusts the view, zoom, what is visible, etc.
{
  view 50 135
  zoom 2
  viewcenter 0 -0.042
  autoscale off
  valuerange -0.25 1.25
  palette 3
  keys A
  keys !
  keys m
  subdivisions 7 1
}

# this section creates screenshots from a sequence of meshes/solutions
{
  screenshot solution.00.png

solution mesh.01 solution.01  screenshot solution.01.png
solution mesh.02 solution.02  screenshot solution.02.png
}
```

To run the script use
```
./glvis [options] -run script.glvs
```
and then press `space` to execute one block/section at a time; command blocks are grouped by curly brackets. In the above example all key commands are executed in the first block and then the screenshots can be safely taken without a pause.

Sometimes it can be easier to write a bash script to generate the GLVis script if you have a lot of mesh+solution files. :-)

All available GLVis script commands can found in the code, [here](https://github.com/GLVis/glvis/blob/master/glvis.cpp#L633).

**Comment by martemyev** [comment]
Hi Veselin,

Thank you for the explanation! GLVis scripts seem very cool. I couldn't, however, figure out how to visualize components of a vector field, which I'd do with a '-gc' key in the command line.

Thanks,
Mikhail

**Comment by v-dobrev** [comment]
For 3D vector fields, use the `'F'` key to switch states:
```
magnitude -> x-component -> y-component -> z-component.
```

For 2D vector fields, use a combination of the `'U'` and `'u'` keys - first use `'U'` twice to get the message
```
Key 'u' will: Cycle through vector-to-scalar functions
```
then press the `'u'` key till you get the desired component.

**Comment by martemyev** [comment]
To clarify, if I want to save a snapshot of a y-component of a 2D vector field, I need to include this line in the .glvs script:
```
keys UUuuu
```
It's not as intuitive as '-gc 1' in the command line, but it works. Thanks a lot!

Cheers,
Mikhail

**Comment by martemyev** [comment]
Okay, so I'm a bit confused with the following. When I use the script like this to save first an x- and then a y-component of a 2D vector solution:
```bash
# Visualization window geometry
window 0 0 1200 800 

# Initial solution
solution mesh.000000 mode_00.000000

# Setup the GLVis scene. Executed after pressing the space bar.
{
   perspective off 
   light off 
   view 0 0 
   viewcenter 0 0 
   zoom 1.5 
   keys R
}

# Take multiple screenshots. Executed after pressing the space bar.
{
   keys UUuu
   screenshot mode_1x_mfem.png
   keys u
   screenshot mode_1y_mfem.png
}
```
I got the following output in the terminal:
```bash
Script: solution: mesh: mesh.000000; solution: mode_00.000000
Subdivision factors = 14, 1
Shading type : non-conforming (with subdivision)
Script: perspective: off
Script: light: off
Script: view: 0 0
Script: viewcenter: 0 0
Script: zoom: 1.5
Script: keys: 'R'
Script: keys: 'UUuu'
Script: screenshot: -> mode_1x_mfem.png
Key 'u' will: Decrease vector subdivision factor
Key 'u' will: Cycle through vector-to-scalar functions
Vector-to-scalar function: direction
Vector-to-scalar function: x-component
Script: keys: 'u'
Script: screenshot: -> mode_1y_mfem.png
Vector-to-scalar function: y-component
```
so first a snapshot is saved, and then a key sequence is executed. So, in this particular example, `mode_1x_mfem.png` shows the magnitude of the vector field, and `mode_1y_mfem.png` - the x-component.
What am I doing wrong?
Isn't this behavior related to the commented out line https://github.com/GLVis/glvis/blob/master/glvis.cpp#L924 ?

Thanks,
Mikhail

**Comment by martemyev** [comment]
An edit to the previous post - the files `mode_1x_mfem.png` and `mode_1y_mfem.png` both show the magnitude of the vector field.
Also, the following script works as expected:
```bash
# Visualization window geometry
window 0 0 1200 800 

# Initial solution
solution mesh.000000 mode_00.000000

# Setup the GLVis scene. Executed after pressing the space bar.
{
   perspective off 
   light off 
   view 0 0 
   viewcenter 0 0 
   zoom 1.5 
   keys Rc
}

# Take multiple screenshots. Executed after pressing the space bar.
{
   keys UUuu
}
{
   screenshot mode_1x_mfem.png
}
{
   keys u
}
{
   screenshot mode_1y_mfem.png
}
```

**Comment by v-dobrev** [comment]
Hi Mikhail,

I pushed some changes to the develop branch to address the issue with the keys - with this change there is no need to pause after `keys` command to wait for the screen update before using `screenshot`.

Let us know if you encounter any problems with these modifications.

**Comment by martemyev** [comment]
Hi Veselin,

It works now. Thanks a lot!

Cheers,
Mikhail
