### ISSUE TITLE
Title or legend

### ISSUE THREAD

**Issue by martemyev** [GLVis/glvis#14]
Dear All,

Is it possible to put a text in a GLVis graphics window that then will be saved as a snapshot? The text can represent a title of a simulation result or a legend.

Thanks,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

It is possible to add something like this, but the interface will be probably quite restrictive... isn't it more flexible if you just any text you like to the saved screenshots later, e.g. with ImageMagick's convert?

Cheers,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

I believe legends are quite convenient and informative especially when they are combined with a color bar in the same window. If adding a text is not straightforward, could you please share an example of how `convert` can be used for adding a text?

I'm also curious what you meant by "the interface will be probably quite restrictive...".

Thanks,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

Can you propose how to set these from the GLVis window and what would you like to be displayed?  

The `convert` utility has tons of options, see e.g. http://www.imagemagick.org/Usage/annotating. It is very likely already installed on your system. Here is one example of adding text:
```
convert input.png -annotate +10+10 "My Caption" output.png
```

**Comment by martemyev** [comment]
> Can you propose how to set these from the GLVis window and what would you like to be displayed?

If there would be a way to set a field name, this name could be displayed on top of the color bar (similar to VisIt and ParaView). It may be a function analogous to `VisItDataCollection::RegisterField` or simply:
```cxx
   ofstream sol_ofs("sol.gf");
   sol_ofs << "Fieldname " << field_name << "\n";
   sol_ofs.precision(8);
   x.Save(sol_ofs);
```
Then, from the GLVis window a user can select a component to be visualized (for example, for 2D vector field pressing 'UUuu' and so on), and a component that is currently shown would be added to a field name. For example, if the field name is "Velocity", the default view is "Velocity magnitude", then when x-component is selected "Velocity x-component", or similar. The same with divergence, curl, etc. That would be really helpful.

Thank you for the `convert` example.

Cheers,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

We should have something in GLVis that address your request early next week. Stay tuned...

Tzanio

**Comment by tzanio** [comment]
Hi Mikhail,

I committed something in 415ab30ec8422e827987951b18fe8df8c528707c. Let us know if this meets your needs.

Cheers,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

Thanks for the commit. It looks very nice, and it's much more informative now.

Thanks,
Mikhail

**Comment by tzanio** [comment]
Great! Let us know if you have any further suggestions.

Tzanio
