### ISSUE TITLE
bdr_el_attr_to_show segfault

### ISSUE THREAD

**Issue by camierjs** [GLVis/glvis#144]
In [VisualizationSceneSolution::PrepareBoundary](https://github.com/GLVis/glvis/blob/230df6bf929016f63d4ca135b1ac08ea1fa2a97d/lib/vssolution.cpp#L2146), I'm hitting the case where `GetNBE > 0`, `shading == 2`,  the mesh has `GetBdrAttribute` but the `bdr_el_attr_to_show` size is set to `0`.

I may be doing something wrong, but shouldn't we try to avoid to segfault on this?

**Comment by tzanio** [comment]
That should generally be OK (not showing any of the boundary).

Can you post what the error is? Is the size of `bdr_el_attr_to_show` correct (should be `mesh->bdr_attributes.Max()`)?

**Comment by camierjs** [comment]
`bdr_el_attr_to_show` size is `0`  from https://github.com/GLVis/glvis/blob/230df6bf929016f63d4ca135b1ac08ea1fa2a97d/lib/vssolution.cpp#L471 and `mesh->GetBdrAttribute(i)` gives us back a `1`.

**Comment by tzanio** [comment]
It sounds like the mesh may be in inconsistent state where the boundary attributes (`Mesh::bdr_attributes`) are empty, but there are boundary elements (`Mesh::boundary`).

How was this mesh constructed, in particular was `Mesh::SetAttributes()` called?

What does `mesh->GetNBE()` return?

**Comment by camierjs** [comment]
The starting mesh is `data/periodic-square.mesh` and elements get refined randomly, some might be on the boundary.
We start with no attributes, no boundary elements. Some of them must be added in the process.

**Comment by tzanio** [comment]
I see.

It certainly wouldn't hurt to add a check in the beginning of `VisualizationSceneSolution::PrepareBoundary()`:

```c++
if (bdr_el_attr_to_show.Size() == 0) { return; } // the mesh has no boundary
```

If you want, propose a PR for it (I can do it too).

That being said, `periodic-square.mesh` describes a closed domain without boundary and so `mesh->GetNBE()` should always return zero. In general refinement should create boundary elements only by refining existing boundary elements, in particular it shouldn't create boundary element if none previously existed.

Does this make sense?

**Comment by camierjs** [comment]
Starting with a periodic and adding AMR refinements leads to this issue.

**Comment by tzanio** [comment]
@jakubcerveny do you envision any issues with NC refinement of periodic meshes (see above)?

**Comment by jakubcerveny** [comment]
I don't think there should be any issue with periodic NC meshes. In that case the NCMesh is topology only and doesn't care about the Nodes, it should "just work", with no boundary elements. I think I've seen ex9 work nicely with random refinements. Of course there could be some bug, so if you can reproduce e.g. a case where boundary elements are created out of nowhere, I can help debug that.

**Comment by tzanio** [comment]
thanks Jakub

**Comment by tzanio** [comment]
@camierjs, how should we proceed with this?

**Comment by camierjs** [comment]
You must be right @jakubcerveny, I can't reproduce it with my current state of `Laghos`, `Remhos` and the `mfem` amr examples.
