### ISSUE TITLE
Error reports when running meshes using MFEM example 2 with GLVis

### ISSUE THREAD

**Issue by jhoy97** [GLVis/glvis#148]
I am working on a cantilever beam problem in both 2D & 3D, and after modelling and meshing the problem on Gmsh, these error reports show:
MFEM abort: Non-positive element attribute in Gmsh mesh!
... in function: void mfem::Mesh::ReadGmshMesh(std::istream&)
... in file: mesh/mesh_readers.cpp:1172
Abort (core dumped)

MFEM abort: Gmsh file : vertex index doesn't exist
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&)
 ... in file: mesh/mesh_readers.cpp:1164

After designing the beam in Gmsh and exporting the .msh file and running it with ex2.cpp, the error codes show and no glvis window appears.  Is there a particular way to export the files?

**Comment by tzanio** [comment]
The Gmsh boundary attributes should be positive, in particular they can't be zero.
