### ISSUE TITLE
GLVis in MS Windows

### ISSUE THREAD

**Issue by ricunha** [GLVis/glvis#15]
I’m interested use MFEM and GLVis to do some experimented.
But my work platform is MS Windows. I read that MFEM can work on it but GLVis will work only on in X11 bases.
I’m writing you to ask how I can see the MFEM results without GLVis ou how can I make GLVis work in Windows.
Thanks in advance!
Ricardo

**Comment by tzanio** [comment]
Hi Ricardo,

You can make GLVis work on WIndows if you install [Cygwin](https://www.cygwin.com) and build it under that. This will be the best approach if you want to use it as a socket server.
If you just want to visualize MFEM results saved in files, a simpler option may be to use [VisIt][http://visit.llnl.gov], which has a Windows executable and supports mfem output through the VisItDataCollection class, see e.g. Examples 5 and 9.

Hope this helps,
Tzanio

**Comment by ricunha** [comment]
Ok! I will try!
