### ISSUE TITLE
Can we overlay multiple solutions and meshes?

### ISSUE THREAD

**Issue by sshiraiwa** [GLVis/glvis#150]
I am wondering if one can generate a figure like this one https://mfem.org/img/gallery/nstxu_hhfw.png, which is made from two solutions and one mesh file,  inside GLVis :-D?

**Comment by tzanio** [comment]
The short answer is: "currently NO" :(

The long answer is that GLVis does support all the required tools -- computing grid function in a cutting plane, showing part of the mesh, etc. but it does not have a user interface to define and combine them, e.g. only one cutting plane is defined and can be manipulated.

It is always tricky where to draw the line between a fast/simple tool like GLVis and a more full-fledged vis environment as VisIt and ParaView 😁

**Comment by tzanio** [comment]
That being said, you can *totally* visualize separate parts in separate windows

**Comment by tzanio** [comment]
I wouldn't recommend it to everyone, but it also possible to hack GLVis for a particular plot. That's how this image was generated: https://glvis.org/img/gallery/tp-3d-ale-black.png

**Comment by psocratis** [comment]
@sshiraiwa , if you just need just visualization of 2 or more meshes/solution on the same window you can play the "parallel" trick. Something like this would do it 

````cpp
   for (int i = 0 ; i<nrsub; i++)
   {
      socketstream sol_sock(vishost, visport);
      sol_sock.precision(8);
      sol_sock << "parallel " << nrsub << " " << i << "\n";
      sol_sock << "solution\n" << *Meshes[i] << *gf[i] << flush;
   }
````

Thanks, 

Socratis

**Comment by sshiraiwa** [comment]
Hi all, Thank you for your suggestions and clarification.
