### ISSUE TITLE
Unable to build in windows (using vcpkg)

### ISSUE THREAD

**Issue by lmdiazangulo** [GLVis/glvis#155]
Hi,

I am having problems building in windows using vcpkg libraries. I don't know if that is the recommended procedure and would appreciate if somebody could point me to a better one if it is not.

Following this procedure, most of my problems seem to be related with pthreads. 

I found a first issue with CMakeLists.txt not being able to detect that pthreads was found. I could fix that with: 
```   find_package(Threads REQUIRED)
-  if (NOT CMAKE_USE_PTHREADS_INIT)
+  if (NOT PTHREADS_LIBRARY)
     message(FATAL_ERROR "The required pthreads library was not found.")
   else()
     list(APPEND _glvis_libraries "${CMAKE_THREAD_LIBS_INIT}")
```
Once cmake finished, the build found problems due to undefined M_PI which can be fixed with:
`+  add_definitions(-D_USE_MATH_DEFINES)`

However, I have come to a dead end because of the <unistd.h> dependency in threads.cpp as I can't find an equivalent in windows.

Thanks for your work. Your code buillt and run like a charm for me under linux.

**Comment by v-dobrev** [comment]
I'm not familiar with vcpkg. Is it using the visual studio compiler? I'm not sure it provides pthreads support which is needed by GLVis.

Typically, people using GLVis under windows use WSL, I think.

**Comment by kennyweiss** [comment]
@lmdiazangulo  -- in case this is helpful, the Axom project (https://github.com/LLNL/axom) also depends on mfem.

We've developed a `vcpkg` port for `mfem@4.0` for our Windows build, see: https://github.com/LLNL/axom/tree/develop/scripts/uberenv/vcpkg_ports/mfem

I don't recall dealing with pthreads or `unistd`, but for other windows/unix capabilities, we depend on `direct.h`, so that might be a good place to look if glvis needs to be patched. See, e.g.:
https://github.com/LLNL/axom/blob/fe0f07e5525bf1cda91e6be1399edf18741843cb/src/axom/core/utilities/FileUtilities.cpp#L15-L29

We also had to build mfem as a shared library (dll) due to complications related to building `hdf5` and `gtest` on Windows.

**Comment by lmdiazangulo** [comment]
> I'm not familiar with vcpkg. Is it using the visual studio compiler? I'm not sure it provides pthreads support which is needed by GLVis.
> 
> Typically, people using GLVis under windows use WSL, I think.

VCPKG is basically a cross-platform c/c++ package manager. I find it quite usefull, especially for these kind of projects which depend on so many external libraries. I could use it yesterday (partially) successfully with MFEM. I have used it only for one week or so (so no expert here), but I think I really like it, both for windows and linux.

I did not know about WSL, thanks for pointing me there. I understand it is a concept similar to mingw or cygwin, basically adding a layer of linux on top of windows. I was trying was a native compilation in windows, but I guess it won't be possible.

Thanks for your answer.

**Comment by lmdiazangulo** [comment]
> @lmdiazangulo -- in case this is helpful, the Axom project (https://github.com/LLNL/axom) also depends on mfem.
> 
> We've developed a `vcpkg` port for `mfem@4.0` for our Windows build, see: https://github.com/LLNL/axom/tree/develop/scripts/uberenv/vcpkg_ports/mfem
> 
> I don't recall dealing with pthreads or `unistd`, but for other windows/unix capabilities, we depend on `direct.h`, so that might be a good place to look if glvis needs to be patched. See, e.g.:
> https://github.com/LLNL/axom/blob/fe0f07e5525bf1cda91e6be1399edf18741843cb/src/axom/core/utilities/FileUtilities.cpp#L15-L29
> 
> We also had to build mfem as a shared library (dll) due to complications related to building `hdf5` and `gtest` on Windows.

I have  tried a little bit more, with pasting your code, and some unistd.h ports that I have found ([this one](https://stackoverflow.com/questions/341817/is-there-a-replacement-for-unistd-h-for-windows-visual-c#:~:text=Try%20including%20the%20io.,h%20.)),

That tweak seemed to fix some issues but now the problematic part is fcntl. I don't know about that function but I did a little bit of research and it seems that it is not easily replaced under windows. It would require to change a signficant amount of code and I think I can do much more damage than good if I do so. 

I did not know about axiom. I have taken a look on it (specially the part of meshes) and seems very interesting. Thanks for showing it to me.

**Comment by lmdiazangulo** [comment]
> Typically, people using GLVis under windows use WSL, I think.

I have tried using WSL2 and worked well.  Thanks for that suggestion.

**Comment by tzanio** [comment]
I am closing this, but it may be good to add support for vcpkg in both MFEM and GLVis in the future...
