### ISSUE TITLE
error building glvis against mfem with cuda enabled

### ISSUE THREAD

**Issue by cwsmith** [GLVis/glvis#157]
On a RHEL7 workstation using cuda 10.2 and gcc 7.4 I built mfem master@b077091 with cuda enabled via cmake then attempted to build glvis master@9ea76c7 against it.  That resulted in the following compilation error:

```
[ 29%] Building CXX object lib/CMakeFiles/glvis.dir/aux_vis.cpp.o
cd /space/cwsmith/omegahMfem/build-glvis/lib && /opt/scorec/spack/v0132/install/linux-rhel7-x86_64/gcc-6.5.0/gcc-7.4.0-c5aaloybb5jqiolgakbf5sxir4axkly4/bin/g++  -DGLVIS_MS_LINEWIDTH=1.4 -DGLVIS_MULTISAMPLE=4 -DGLVIS_USE_LIBP
NG -isystem /space/cwsmith/omegahMfem/build-mfem-cuda-noOmega/install/include -isystem /opt/scorec/spack/v0132/install/linux-rhel7-x86_64/gcc-7.4.0/mpich-3.3.1-bfezl2lt55nkqq3x7o5364rlvbknynka/include -isystem /opt/scorec/sp
ack/v0132/install/linux-rhel7-x86_64/gcc-7.4.0/metis-5.1.0-aozm7niibrgejx6cfraiyh23jzgb6nrm/include -isystem /opt/scorec/spack/v0132/install/linux-rhel7-x86_64/gcc-7.4.0/hypre-2.18.1-y2p4vsysvovlj2va346lutvmfkn6tpin/include 
-isystem /space/cwsmith/omegahMfem/build-sdl2/install/include -isystem /space/cwsmith/omegahMfem/glm -isystem /space/cwsmith/omegahMfem/build-glew-cmake/install/include -isystem /opt/scorec/spack/v0132/install/linux-rhel7-x8
6_64/gcc-7.4.0/zlib-1.2.11-quahr4cc5oc2ooudp2v7xn3wbskoruef/include -isystem /usr/include/freetype2  -O3 -DNDEBUG   -std=c++11 -o CMakeFiles/glvis.dir/aux_vis.cpp.o -c /space/cwsmith/omegahMfem/glvis/lib/aux_vis.cpp
In file included from /space/cwsmith/omegahMfem/build-mfem-cuda-noOmega/install/include/mfem/linalg/linalg.hpp:20:0,
                 from /space/cwsmith/omegahMfem/build-mfem-cuda-noOmega/install/include/mfem/mfem.hpp:41,
                 from /space/cwsmith/omegahMfem/build-mfem-cuda-noOmega/install/include/mfem.hpp:2,
                 from /space/cwsmith/omegahMfem/glvis/lib/aux_vis.cpp:18:
/space/cwsmith/omegahMfem/build-mfem-cuda-noOmega/install/include/mfem/linalg/sparsemat.hpp:25:10: fatal error: cusparse.h: No such file or directory
 #include <cusparse.h>
          ^~~~~~~~~~~~
compilation terminated.
```

The mfem cmake command is:

```
cmake /path/to/mfem/ \
-DCMAKE_BUILD_TYPE=DEBUG \
-DCMAKE_CUDA_FLAGS_DEBUG='-g -O0' \
-DMFEM_USE_MPI=ON \
-DMFEM_USE_METIS_5=ON \
-DMETIS_DIR=${METIS_DIR} \
-DMFEM_USE_CUDA=ON \
-DCUDA_ARCH=sm_75 \
-DMPI_CXX_COMPILER=`which mpicxx` \
-DCMAKE_INSTALL_PREFIX=$PWD/install
```

and the glvis cmake command is (the dependencies paths are listed in `CMAKE_PREFIX_PATH`):

```
cmake ../glvis \
    -D CMAKE_BUILD_TYPE:STRING=Release \
    -D CMAKE_INSTALL_PREFIX:STRING=$PWD/install \
    -D GLVIS_USE_LIBTIFF=OFF \
    -D GLVIS_USE_LIBPNG=ON \
    -D MFEM_DIR=$mfem
```

Please let me know if additional environment details are needed.

Is this combination supported?

**Comment by v-dobrev** [comment]
Since we are using the host compiler to build GLVis, we probably need to add the CUDA include dir and explicitly link with the CUDA libraries we use. Another option could be to try to build everything with `nvcc`, similar to the way we build mfem examples and miniapps.

**Comment by tzanio** [comment]
This may be not be convenient from a workflow perspective, but it is probably best to have a separate "plain" version of MFEM without CUDA or MPI enabled and use that just to build GLVis. 

There is really no benefit from these currently in GLVis, and they may in fact complicate matters.

**Comment by cwsmith** [comment]
Thanks @v-dobrev and @tzanio.  Can GLVis built with a 'plain' MFEM be used to render output (meshes and fields) from a CUDA enabled MFEM build?

**Comment by tzanio** [comment]
> Can GLVis built with a 'plain' MFEM be used to render output (meshes and fields) from a CUDA enabled MFEM build?

Yes

**Comment by tzanio** [comment]
See also https://glvis.org/live/

**Comment by cwsmith** [comment]
Great.  Thank you.

The vis site is pretty slick.  We'll try that.

I'm all set; feel free to close this issue.

**Comment by tzanio** [comment]
We have not announced it officially yet, but you can see some more info about the web version here: https://github.com/GLVis/glvis-js/tree/master/live.

Let us know at https://github.com/GLVis/glvis-js if you find any issues with it.

**Comment by sshiraiwa** [comment]
This is very very COOL 😎
