### ISSUE TITLE
parallel nurbs mesh issue

### ISSUE THREAD

**Issue by rduvigne** [GLVis/glvis#16]
Hello,

I encountered problems when trying to visualize a grid based on nurbs elements from a set of files.
It works well when using a single file, but when using multiple files only the grid contained in the last file is actually visible.

I would like to know if you have an example corresponding to such a case ?
If necessary, I can also provide my case to fix the problem.

Thanks a lot.
Regis

**Comment by tzanio** [comment]
Hi Regis,

This should work. 

One way to try it is to run [MFEM's](http://mfem.org) Example 1p on a NURBS mesh:
```
mpirun -np 2 ex1p -m ../data/pipe-nurbs.mesh
```
This produces files `mesh.000000`, `mesh.000001`, `sol.000000` and `sol.000001` [(attached)](https://github.com/GLVis/glvis/files/779095/Ex1p-NURBS.zip), that can then be visualized with
```
glvis -np 2 -m mesh -g sol
``` 

How do you generate your mesh? Can you send us a sample?

Cheers,
Tzanio

**Comment by rduvigne** [comment]
Thanks a lot for this fast reply and confirmation that it should work !

I check the program that writes the partitioned nurbs grid (my own work).
I will send you a small example if I do not succeed in fixing the problem.

Regards,
Régis

**Comment by rduvigne** [comment]
Hi,

In fact your example is a little too complex to analyse my error. Could you generate a similar one from the case data/square-disc-nurbs.mesh ? (I have not compiled MFEM in parallel).

Alternatively, I have generated a very simple case (2 elements) that illustrates my problem
[test_nurbs.zip](https://github.com/GLVis/glvis/files/780797/test_nurbs.zip)

The two files corresponding to quad elements works well. But for the two files with nurbs elements, only the element contained in the second file is visible. if you visualize the files separately, both case work.
The only difference between quad and nurbs is in the definition of edges. Could you explain me what is wrong ?

Thanks in advance,
Régis

**Comment by tzanio** [comment]
Hi Régis,

Is [this test case](https://github.com/GLVis/glvis/files/781771/Ex1p-NURBS.zip) better?

It is just the `data/beam-quad-nurbs.mesh` split in two:
![glvis_s01](https://cloud.githubusercontent.com/assets/1278247/23045466/8622a81e-f459-11e6-8ac7-2040e5a8930b.png)

Tzanio

**Comment by v-dobrev** [comment]
Hi Régis,

Note that when MFEM writes a parallel NURBS mesh, each processor writes the global patch connectivity as a mesh of quads/hexes; then each processor writes all knot vectors. Then each processor writes its local elements in a section called `mesh_elements` (which is not used in serial) and finally, its local weights and control point coordinates.

Hope this helps,
Veselin

**Comment by rduvigne** [comment]
Hi,
Thank you for your help, my bug is fixed now (I misunderstood the "mesh_elements" section)
Here is an example of partitioned nurbs grid to study the flow around an airfoil:

![mesh_nurbs_16part](https://cloud.githubusercontent.com/assets/25796375/23070753/7693c198-f52c-11e6-93e3-e5a5c8e0d44e.png)

By the way, GLVIS is a perfect tool for visualization in isogeometric analysis !
Thanks again for your help.
régis

**Comment by tzanio** [comment]
Glad you got it working.

Thank you for the good words and please let us know if you have any questions or feature requests in the future.

Tzanio
