### ISSUE TITLE
std::unique_ptr::reset causes runtime error 

### ISSUE THREAD

**Issue by tomstitt** [GLVis/glvis#162]
https://github.com/GLVis/glvis/pull/153 changed the `stream_state` to use a `std::unique_ptr`s for, among other things, the `GridFunction` `grid_f`. In the web target the `std::unique_ptr::reset` in https://github.com/GLVis/glvis/blob/master/lib/aux_js.cpp#L193 causes a runtime error that prevents the loading of example 3:

```
[Log] Switching to order 1 discontinuous vector grid function... (glvis.js, line 2293)
[Error] Unhandled Promise Rejection: RuntimeError: call_indirect to a signature that does not match (evaluating 'invoker(fn, arg0Wired, arg1Wired, arg2Wired, arg3Wired)')
	(anonymous function)
	promiseReactionJob
```

Removing the `reset` and passing the pointer to the `VisualizationSceneVector3d` "fixes" the issue in that the rendering actually happens. Here's the diff:

```
--- a/lib/aux_js.cpp
+++ b/lib/aux_js.cpp
@@ -190,8 +190,8 @@ bool startVisualization(const std::string input, const std::string data_type,
          {
             GridFunction* proj_grid_f = ProjectVectorFEGridFunction(
                                            stream_state.grid_f.get());
-            stream_state.grid_f.reset(proj_grid_f);
-            vs = new VisualizationSceneVector3d(*stream_state.grid_f);
+            //stream_state.grid_f.reset(proj_grid_f);
+            vs = new VisualizationSceneVector3d(*proj_grid_f);
          }
          else
```

This seems like a problem with either Emscripten or how we're building the web target but I wanted to start a discussion here.

**Comment by kanye-quest** [comment]
The bug seems to be a problem in the glvis core itself rather than a js-related issue; I pushed out a PR that should fix the issue.
