### ISSUE TITLE
How to display .msh(Gmsh) file?

### ISSUE THREAD

**Issue by CODER591** [GLVis/glvis#172]
Hello, 
I am a total newbie in meshing topics
I have created a simple mesh using `gmsh`. Saved as ASCII version 4.
It is a simple meshed square (5x5)
![Screenshot from 2021-05-14 12-51-22](https://user-images.githubusercontent.com/33939665/118253887-22beb000-b4b3-11eb-95d4-44393b10af23.png)
I have built `glvis`  binary  and tried to use:
`glvis -m filename.msh`

But it failed with the following error:
![Screenshot from 2021-05-14 12-41-37](https://user-images.githubusercontent.com/33939665/118252761-c8711f80-b4b1-11eb-897a-707104ee7cae.png)

Question is:
1. What I have done wrong? [(Based on this tutorial)](https://www.youtube.com/watch?v=xL2LmDsDLYw&ab_channel=QuickerSimLtd)
2. How to convert `.msh (gmsh)` format to the `.mesh` format (your custom)
The `.mesh` and `.geo` files are attached.

[exported_fine.msh.txt](https://github.com/GLVis/glvis/files/6478000/exported_fine.msh.txt)
[fine.geo.txt](https://github.com/GLVis/glvis/files/6478001/fine.geo.txt)

**Comment by CODER591** [comment]
As per https://github.com/mfem/mfem/issues/2216
MFEM (glvis) supports only the GMSH (Version ASCII 2)

**Comment by v-dobrev** [comment]
It looks like we need a version check with better error message. 😄

**Comment by CODER591** [comment]
Sorry for the offtop, but small proposition:
1. Specify at the https://mfem.org/meshing/ page that that mesh format would be detected automatically on input
2. Specify [here](https://mfem.org/mesh-formats/) or [here](https://mfem.org/meshing/) about software that could generate meshes in MFEM format? (if it exist)
Thanks!

**Comment by tzanio** [comment]
Sorry for the confusion @CODER591, we've been meaning to add support for Gmsh 4 for a while now, but other things have been higher priority: https://github.com/mfem/mfem/issues/678.

Are you willing to help us improve the documentation by implementing your suggestions above?

If so, feel free to open PR in https://github.com/mfem/web. The website sources are simple Markdown files, e.g. https://github.com/mfem/web/blob/master/src/meshing.md.

Thanks!
Tzanio

**Comment by CODER591** [comment]
I will take a look at the implementing suggestions, thanks for the answers!
