### ISSUE TITLE
Update GLVis Spack package

### ISSUE THREAD

**Issue by tzanio** [GLVis/glvis#173]
We should update the Spack package for GLVis to support version 4.0+

**Comment by tzanio** [comment]
@tomstitt, are you still interested in working on this?

**Comment by tomstitt** [comment]
I still have more testing to do but I have started this [here](https://github.com/tomstitt/spack/tree/glvis-4) and have tested on os x

**Comment by tomstitt** [comment]
merged: https://github.com/spack/spack/pull/25045

**Comment by tzanio** [comment]
thanks @tomstitt 🙏
