### ISSUE TITLE
Cannot visualize mfem running result with glvis

### ISSUE THREAD

**Issue by likangan** [GLVis/glvis#175]
Hi,

I am running glvis and mfem on my mac. mfem example code can run to the end, but glvis doesn't show the result and gives an error info as
objc[76538]: +[NSApplication initialize] may have been in progress in another thread when fork() was called.
objc[76538]: +[NSApplication initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
what can be the problem with this? thank you

**Comment by tzanio** [comment]
This is due to https://github.com/GLVis/glvis/discussions/141.

Sorry, we are working on fixing that, but that requires significant restructuring. Note that this affects only macOS Catalina and later, there are no issues on Linux.

In the meantime, can you try downgrading SDL2 as described here: https://github.com/GLVis/glvis/discussions/141#discussioncomment-667221.

Tzanio

**Comment by likangan** [comment]
Thank you, I set SDL2 library manually, following step by step, but still got the same issue.

**Comment by tzanio** [comment]
You did rebuild `glvis`?

**Comment by likangan** [comment]
Yes, I rebuilt it.

**Comment by tzanio** [comment]
Hmm... I'm not sure what's different for you.

What is the output of the following commands in the top `glvis` directory:

- `make info`
- `grep SDL_MAJOR_VERSION ../SDL2/include/SDL2/*`
- `grep SDL_MINOR_VERSION ../SDL2/include/SDL2/*`
- `grep SDL_PATCHLEVEL ../SDL2/include/SDL2/*`
- `make distclean; make`

**Comment by likangan** [comment]
make info

MFEM_DIR    = ../mfem
GLVIS_FLAGS =  -O3 -std=c++11 -I../mfem -I../mfem/../hypre/src/hypre/include -I../mfem/../metis-5.0/include  -DGLVIS_MULTISAMPLE=4 -DGLVIS_MS_LINEWIDTH=1.0 -DGLVIS_OGL3 -I/opt/X11/include/freetype2 -I/usr/local/include -I/usr/local/include -I/Users/Documents/summer/glm  -DGLVIS_USE_LIBPNG
GLVIS_LIBS  = $(MFEM_LIBS) $(GL_LIBS) $(PNG_LIBS) $(PTHREAD_LIB)
GLVIS_LIBS  = -L../mfem -lmfem -L../mfem/../hypre/src/hypre/lib -lHYPRE -L/usr/local/lib/ -lmetis -L/opt/X11/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib  -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lfreetype -lfontconfig -lSDL2 -lGLEW -framework OpenGL -framework Cocoa -lpng -lpthread
PREFIX      = ./bin

grep SDL_MAJOR_VERSION ../SDL2/include/SDL2/*

../SDL2/include/SDL2/SDL_version.h:#define SDL_MAJOR_VERSION   2
../SDL2/include/SDL2/SDL_version.h:    (x)->major = SDL_MAJOR_VERSION;                 \
../SDL2/include/SDL2/SDL_version.h:    SDL_VERSIONNUM(SDL_MAJOR_VERSION, SDL_MINOR_VERSION, SDL_PATCHLEVEL)

grep SDL_MINOR_VERSION ../SDL2/include/SDL2/*

../SDL2/include/SDL2/SDL_version.h:#define SDL_MINOR_VERSION   0
../SDL2/include/SDL2/SDL_version.h:    (x)->minor = SDL_MINOR_VERSION;                 \
../SDL2/include/SDL2/SDL_version.h:    SDL_VERSIONNUM(SDL_MAJOR_VERSION, SDL_MINOR_VERSION, SDL_PATCHLEVEL)

grep SDL_PATCHLEVEL ../SDL2/include/SDL2/*

../SDL2/include/SDL2/SDL_version.h:#define SDL_PATCHLEVEL      12
../SDL2/include/SDL2/SDL_version.h:    (x)->patch = SDL_PATCHLEVEL;                    \
../SDL2/include/SDL2/SDL_version.h:    SDL_VERSIONNUM(SDL_MAJOR_VERSION, SDL_MINOR_VERSION, SDL_PATCHLEVEL)

**Comment by likangan** [comment]
Thank you, we solved it. Just need to uninstall all the versions of SDL, and try your specific version again.

**Comment by tzanio** [comment]
Awesome, I glad you were able to resolve it!
