### ISSUE TITLE
Cannot compile glvis 4.1 on windows

### ISSUE THREAD

**Issue by ChaoW95** [GLVis/glvis#203]
I opened` glvis 4.1` as a project in Clion.
The compiler is Mingw 8.1.
When I tried to build the executable, I following errors showed.

====================[ Build | glvis-exe | Release ]=============================
"C:\Program Files\JetBrains\CLion 2021.2.2\bin\cmake\win\bin\cmake.exe" --build C:\Users\chaow\OneDrive\Desktop\FEM\glvis-4.1\cmake-build-release --target glvis-exe -- -j 1
Scanning dependencies of target glvis
[  3%] Building CXX object lib/CMakeFiles/glvis.dir/aux_vis.cpp.obj
In file included from C:\Users\chaow\OneDrive\Desktop\FEM\glvis-4.1\lib\threads.hpp:18,
                 from C:\Users\chaow\OneDrive\Desktop\FEM\glvis-4.1\lib\visual.hpp:25,
                 from C:\Users\chaow\OneDrive\Desktop\FEM\glvis-4.1\lib\aux_vis.cpp:22:
C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/thread: In function 'bool std::operator==(std::thread::id, std::thread::id)':
C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/thread:273:26: error: no match for 'operator==' (operand types are 'std::thread::native_handle_type' {aka '__ptw32_handle_t'} and 'std::thread::native_handle_type' {aka '__ptw32_handle_t'})
     return __x._M_thread == __y._M_thread;
            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
In file included from C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/iosfwd:40,
                 from C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/ios:38,
                 from C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/ostream:38,
                 from C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/iostream:39,
                 from C:\Users\chaow\OneDrive\Desktop\FEM\glvis-4.1\lib\aux_vis.cpp:12:
C:/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/bits/postypes.h:216:5: note: candidate: 'template<class _StateT> bool std::operator==(const std::fpos<_StateT>&, const std::fpos<_StateT>&)'
     operator==(const fpos<_StateT>& __lhs, const fpos<_StateT>& __rhs)
     ^~~~~~~~

**Comment by v-dobrev** [comment]
According to the error messages posted above, the errors happen at the point where GLVis just includes standard C++ headers like here: https://github.com/GLVis/glvis/blob/92595f9c5ee58e729bc2368d452039eb80eeee56/lib/threads.hpp#L18 and here: https://github.com/GLVis/glvis/blob/92595f9c5ee58e729bc2368d452039eb80eeee56/lib/aux_vis.cpp#L12

So, these look like issues with the compiler, not GLVis.

**Comment by ChaoW95** [comment]
Hi, v-dobrev. Thanks for your reply.
This compiler error was solved by using Msys2 with pacman to install the package.
