### ISSUE TITLE
Can't find mfem

### ISSUE THREAD

**Issue by SamaHans** [GLVis/glvis#209]
I have set `MFEM_DIR` as `C/mfem`, where `mfem` is installed. However, error occurs as 
![image](https://user-images.githubusercontent.com/12651419/142423947-e19148fb-bd43-4e7c-a698-31dbccb8f55f.png)
![image](https://user-images.githubusercontent.com/12651419/142424028-d3a28e33-23f6-4cf6-9146-e412c1ef62d7.png)

**Comment by SamaHans** [comment]
Well, `mfem` is found. But SDL2 library is not found.
![image](https://user-images.githubusercontent.com/12651419/142436516-e6e736f4-85cf-45a8-9434-73de762195da.png)

**Comment by SamaHans** [comment]
Okay, I have installed the missing package via `pacman` and accomplished compiling. But when trying to run it, error comes as
`libwinpthread-1.dll` `libstdc++-6.dll` `libgcc_s_seh-1.dll` `libfontconfig-1.dll` missing.

**Comment by jandrej** [comment]
I assume you are using Windows from the `.dll` shared library suffix. Please make sure your mingw setup provides the appropriate shared libraries.

**Comment by v-dobrev** [comment]
You can also try these steps (using `vcpkg`): https://github.com/GLVis/glvis/blob/92595f9c5ee58e729bc2368d452039eb80eeee56/INSTALL#L152-L172

**Comment by SamaHans** [comment]
Oh my bad. I need to tap in commands.

**Comment by v-dobrev** [comment]
Without command line options, GLVis starts in server mode and accepts TCP connections from other (MFEM based, typically) applications such as `ex1` and `ex1p` from MFEM.

For some of the basics, see https://glvis.org/options-and-use and https://mfem.org/serial-tutorial.
