### ISSUE TITLE
How to load a local file in `https://glvis.org/live/`?

### ISSUE THREAD

**Issue by kinnala** [GLVis/glvis#211]
I have the following file and I'm trying to load it at `https://glvis.org/live/` using the button `Load local file`:
```
MFEM mesh v1.0

#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
#

dimension
2

elements
8
1 3 0 1 10 9
1 3 1 2 11 10
1 3 2 3 12 11
1 3 3 4 13 12
2 3 4 5 14 13
2 3 5 6 15 14
2 3 6 7 16 15
2 3 7 8 17 16

boundary
18
3 1 0 1
3 1 1 2
3 1 2 3
3 1 3 4
3 1 4 5
3 1 5 6
3 1 6 7
3 1 7 8
3 1 10 9
3 1 11 10
3 1 12 11
3 1 13 12
3 1 14 13
3 1 15 14
3 1 16 15
3 1 17 16
1 1 9 0
2 1 8 17

vertices
18
2
0 0
1 0
2 0
3 0
4 0
5 0
6 0
7 0
8 0
0 1
1 1
2 1
3 1
4 1
5 1
6 1
7 1
8 1
```
In Google Chrome developer console I see
```
glvis.js:1411 Unknown data format
glvis.js:1411 MFEM mesh v1.0
```
and nothing happens in the visualization area. How can I load local files and what are the supported formats?

Edit: Is this the wrong repository? Should it be in `GLVis/glvis-js`?

**Comment by kinnala** [comment]
Closing because I found the correct repository at `GLVis/glvis-js`. Sorry about the inconvenience.

**Comment by tzanio** [comment]
No worries, please let us know if you have any questions in the future.

**Comment by tzanio** [comment]
See also https://github.com/GLVis/glvis/discussions/207#discussioncomment-1602589

**Comment by kinnala** [comment]
Thanks. I'm looking into outputting this format from another tool because you have a great support for high order meshes. I'll let you know if it works out.

**Comment by kinnala** [comment]
Just to give here a status update, I was able to use `glvis-js` through `pyglvis` to visualize some linear scalar solutions, and also vectorial solutions: https://github.com/kinnala/scikit-fem/pull/827

Obviously to use it for visualizing high-order fields I would need to do a mapping between the DOF numbering scheme used in my code and the scheme used in MFEM. For example, I read somewhere in the docs that the algorithm to number the edges is essentially "loop over the elements and then locally over the edges" and "give the next free number to the current edge if not assigned already". I might be able to vectorize this to make it efficiently in Python but it will require some careful thinking which I'm not ready for right now.

However, I'm happy that glvis was so easy to use and, in the meanwhile, I'm always able to do some refine->interpolate->project loops to a finer mesh before passing it over to glvis.

**Comment by tzanio** [comment]
You may also want to check FMS, https://github.com/CEED/FMS.
