### ISSUE TITLE
Visualize actual domain boundary of parallel meshes

### ISSUE THREAD

**Issue by HennesHajduk** [GLVis/glvis#223]
Hi,
the following issue has been a minor problem for me, so far I've worked around it, but I figured I might as well ask:
The `b` key allows us to visualize the boundary of a domain but in parallel runs it shows the interfaces between MPI-partitioned domains.
I can see the benefit of this possibility but is there a way in visualizing the actual domain boundary? `Print/SaveAsOne` did not seem to do the trick and the bounding box I get with the `a` key does only do the trick for Cartesian domains.

**Comment by tzanio** [comment]
Hi @HennesHajduk,

Sorry for the delayed response.

This can actually be disabled by setting `print_shared` to `false` in the beginning of `ParMesh::Print`:

https://github.com/mfem/mfem/blob/master/mesh/pmesh.cpp#L4686

This is not exposed to the user currently, but we can expose it e.g. as an optional parameter of `ParMesh::Print`. Will that work for you, or do you have a different preference?

Tzanio

**Comment by HennesHajduk** [comment]
Hi @tzanio,

Thanks for the response, there was no rush!

That's exactly what I needed, awesome! I think this could be useful to some people, would you like me to set up a PR?

**Comment by tzanio** [comment]
PR will be appreciated, thanks @HennesHajduk 😄

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/2961
