### ISSUE TITLE
glvis support for windows

### ISSUE THREAD

**Issue by Srihari-mcw** [GLVis/glvis#226]
For mfem in windows we want to visualise with glvis. For glvis we tried to install and build it in windows. But we werent able to get clear steps on installing and building glvis in windows. Could you please check for the windows support and help us in this regard. Thanks

**Comment by tzanio** [comment]
Hi @Srihari-mcw, did you see this portion of the `INSTALL` file?

https://github.com/GLVis/glvis/blob/master/INSTALL#L140-L172

**Comment by kanye-quest** [comment]
Hi @Srihari-mcw, would you be able to see if this prebuilt executable works for your use case?

https://github.com/GLVis/glvis/suites/6194418518/artifacts/218275001

**Comment by Srihari-mcw** [comment]
Thanks for the responses. I will try executing this and get back to you asap

**Comment by Srihari-mcw** [comment]
Hi. The prebuilt executable helped a great deal in the visualisation of mfem mesh outputs. Thanks
