### ISSUE TITLE
Movies

### ISSUE THREAD

**Issue by salomole** [GLVis/glvis#233]
Hello,

I would like to make a movie by taking several snapshot, but I don't know which command to write in the code for that ?

Best wishes,

**Comment by tzanio** [comment]
Hi @salomole,

If it is a spinning movie, you can press <kbd>S</kbd> while the visualization is rotating (<kbd>Shift</kbd> + <kbd>Left Mouse</kbd>) which will generate a sequence of screenshots: `GLVis_m00*.png`.

For more general movies, you can use a GLVis script. See [this section](https://glvis.org/options-and-use/#glvis-scripts) for a simple example.

Hope this helps,
Tzanio

**Comment by salomole** [comment]
Hello ! Thank you for your answer, but I would like to know the screenshot command to insert in my code (using MFEM). Do you know it ? At each time step, I would like a screenshot (in a 2D plane) of a Gridfunction.

**Comment by v-dobrev** [comment]
Both the stream and the script commands use the format `screenshot <filename.png>`. The stream command is processed here: https://github.com/GLVis/glvis/blob/c092dc8f62a8ce37aa1d738d0d4f5db71f6856fb/lib/threads.cpp#L835
