### ISSUE TITLE
CMake build

### ISSUE THREAD

**Issue by juan42** [GLVis/glvis#24]
Hi,

since i had to recompile my libraries a few times now, i wanted to ask if there is still interest in a CMake build system for glvis to keep it compatible with MFEM?

I have a pretty compact working example which needs work to meet the requirements that the makefile provides. I could file that as a PR if there isn't some internal work done already.

Best regards

**Comment by tzanio** [comment]
@juan42: Please add your code and issue a PR and we will take a look. Thanks!

**Comment by tzanio** [comment]
Resolved by https://github.com/GLVis/glvis/commit/733f67325e70f475772650cde125bb75a618092b.
