### ISSUE TITLE
Scalar fields with MapType INTEGRAL do not display properly

### ISSUE THREAD

**Issue by mlstowell** [GLVis/glvis#248]
The problem is two-fold. First, loading the `GridFunction` in `StreamState` uses `GridFunction::GetNodalValues` which contains an `MFEM_ASSERT` requiring MapType VALUE. Second, the range used in the colorbar is based on minimum and maximum values in the vector of degrees of freedom.

The first problem must be solved in MFEM's `GridFunction` implementation. The second can be addressed in GLVis's `VisualizationSceneSolution3d::FindNewValueRange`.

**Comment by tzanio** [comment]
Thanks for looking into this @mlstowell. See also https://github.com/mfem/mfem/issues/1037
