### ISSUE TITLE
glvis over x2go connection to remote sever results in FATAL: window and/or OpenGL context creation failed.

### ISSUE THREAD

**Issue by justfredje** [GLVis/glvis#255]
I'm trying to use glvis over a x2go session (MATE) to a remote server (CentOS7) where I compiled glvis. 

When I am at the server itself glvis works without issues either in a GNOME or MATE desktop session. Also using nomachine works when working remotely (but has other limitations when using the free version).

However when connection through x2go I get "FATAL: window and/or OpenGL context creation failed." printed on the terminal window where I started glvis.

Not being very savy in these things could someone explain me what I should do to get glvis and x2go work nicely together.
Many thanks upfront !

PS glxgears does work over x2go.

PS2 I also notice that one can visualize in a browser which could be a workaround but I did not find understand how to set this up.

**Comment by v-dobrev** [comment]
Can you try the option `-oldgl`?

**Comment by justfredje** [comment]
Hi,

Thanks for your reply: I tried 

`$ ./glvis -oldgl`

but got the same result.

**Comment by v-dobrev** [comment]
I've never used x2go, so I'm not sure how it works. It sounds like it forwards X11 connections from the remote host to the local host which should be running an X server. What is the OS on the local machine and what X server is it running?

You can also check out the following issue, they may give you come clues:
* https://github.com/GLVis/glvis/issues/112
* https://github.com/GLVis/glvis/issues/218

**Comment by alexmyczko** [comment]
@justfredje i've been successful with xrdp, on debian based system (`apt install xrdp xrdpxorg`)
