### ISSUE TITLE
How to generate isosurface plots?

### ISSUE THREAD

**Issue by jtristano** [GLVis/glvis#267]
I've seen in the gallery  how people generate beautiful isosruface/level surface plots in glvis but I cant find the commands to generate them.   What's the secret to generating level surfaces based on min/max ranges?

Thanks
Joe

**Comment by v-dobrev** [comment]
First, press the `e` key to hide the boundary elements; then press `u`/`U` to move the level set value; to add/remove more level sets use `v`/`V`. This is documented here: https://github.com/GLVis/glvis/blob/master/README.md#key-commands and in the more advanced keys for 3D scalar data, here: https://github.com/GLVis/glvis/blob/master/README.md#3d-scalar-data. You can also use the cutting plane to see inside the level sets (without that you'll probably see just the outermost level set) -- use the `i` key for that (see the above docs). By default, the cutting plane is colored using solution values, however you can hide it with the `E` key (see the docs). The cutting plane can be rotated and moved using `x`/`X`, `y`/`Y`, and `z`/`Z` (see the docs).

**Comment by jtristano** [comment]
Beautiful! Thanks!
