### ISSUE TITLE
Visualization of Hexahedra file format

### ISSUE THREAD

**Issue by altineller** [GLVis/glvis#269]
Hello,

I would like to visualize the output of a custom made software to show a mesh, and its displacement. Namely I have the following files and formats as input:
results file:

MESH board dimension 3 Elemtype Hexahedra Nnode 8
coordinates 
1	 0.000000e+00	 0.000000e+00	 0.000000e+00
2	 1.000000e+00	 0.000000e+00	 0.000000e+00
\---
end coordinates
elements
1	 1	 60	 61	 3	 270	 751	 1003	 271
2	 60	 59	 62	 61	 751	 760	 1174	 1003
\---
end elements

displacements file:

GaussPoints "element_gp" ElemType Hexahedra
Number Of Gauss Points: 1
Natural Coordinates: Internal
End gausspoints
Result "Displacements" "Load Analysis"  1  Vector OnNodes 
ComponentNames "u", "v", "w" 
values
1	 0.000000e+00	 0.000000e+00	 0.000000e+00
2	 -2.329461e-06	 -7.243679e-06	 -7.790406e-08
\...
end values

How would I go about visualizing this tru GLVis? Is there any previosly done work, or would I have to write some software to take the results file and convert it into mfem format?

Which modes/features are more suitable for visualizing mesh displacement?

Any ideas/recomendations/help greatly appreciated.

Best Regards,
C.

**Comment by v-dobrev** [comment]
It looks like you need to write a mesh and data (displacement file -> MFEM grid function file) converters. A good starting point about the MFEM mesh formats is here: https://mfem.org/mesh-formats. The vector grid function format is described as part of the description of the `nodes` section in https://mfem.org/mesh-format-v1.x/#geometry -- e.g. for linear hex elements, one can use the string `H1_3D_P1` for the `FiniteElementCollection`.

Let us know if you need more details about the formats.

**Comment by altineller** [comment]
Yes, my custom mesh generator software now can create meshes that can be vısualızed wıth glvis, after a hard days work.
I have mapped the hexahedral file type to elements of type 5, (cube), also generated boundaries as glvis expects.

I have scanned the  https://mfem.org/mesh-format-v1.x page, but I was unable to find how to create a MFEM grid functon file.
Do we create a fıle that has data on each cell, or can we write a function, based on hexa cells properties assign it or its boundaries color?

Also: There is a file GLVis_coloring.gf
That contains:
FiniteElementSpace
FiniteElementCollection: Const3D
VDim: 1
Ordering: 0

1
0
1
0
1
0
1
0

how does this work? when called with glvis -m file.mesh -g GLVis_coloring.gf it will paint all cells blue.

Best Regards,
Can

**Comment by altineller** [comment]
> It looks like you need to write a mesh and data (displacement file -> MFEM grid function file) converters. A good starting point about the MFEM mesh formats is here: https://mfem.org/mesh-formats. The vector grid function format is described as part of the description of the `nodes` section in https://mfem.org/mesh-format-v1.x/#geometry -- e.g. for linear hex elements, one can use the string `H1_3D_P1` for the `FiniteElementCollection`.
> 
> Let us know if you need more details about the formats.

Never mind my last message. I need more information about H1_3D_P1, H1_3D_P2 and RT_3D_P0 formats.

I have been googling, experimenting, and even reading your source without success to reverse the H1_3D_P1 format for the coloring of cells. Is H1_3D_P1 9 data points for each element?

Best Regards,
Can
