### ISSUE TITLE
Triangular patches when in smoother mode

### ISSUE THREAD

**Issue by altineller** [GLVis/glvis#270]
Hello,

I managed to make my program create MFM mesh, and also create a Const3D solution file, and I am getting the results below:

![Screenshot from 2024-01-31 05-00-14](https://github.com/GLVis/glvis/assets/2217584/b5b7ae34-175e-48f7-bfbf-2372c252daed)

when I press the f key o get the smoother on I get the following results:

![Screenshot from 2024-01-31 05-00-00](https://github.com/GLVis/glvis/assets/2217584/60551198-14e0-45bd-b100-326182bf562f)

Some triangular parts are missing. Does this mean that my mesh is generated wrong? Maybe there is a problem with ordering or reverseness of the boundary?

Any ideas/recomendations/help greatly appreciated.

Best Regards,
C.

**Comment by justinlaughlin** [comment]
Hi @altineller :). I'm still learning GLVis myself so I can't say for sure, but your second image has patterns that look very similar to incorrect cell/face ordering (as a quick sanity check you could permutate your indices and see if those artifacts still appear). Please post your mesh/sol file and I can take a look. If you can generate a smaller example illustrating your problem that would be helpful.

**Comment by altineller** [comment]
Hello @justinlaughlin,

Yes, the ordering of certain boundaries were in wrong order. We have fixed it.

Thank you.
