### ISSUE TITLE
Fatal error building GLVis

### ISSUE THREAD

**Issue by Wayne901** [GLVis/glvis#276]
I have built MFEM 4.6 serially with CMake. Then I build GLVis 4.2 with "make ../MFEM_DIR=xxx -j" and it first says "make: cc: command not found". So i link /usr/bin/cc to /usr/bin/gcc, with gcc version 10.1.0.
However, it then returns the error
![Uploading Snipaste_2024-02-24_20-31-09.png…]()

Or when i install GLVis with CMake with
"tar -zxvf glvis.tgz
 cd glvis
 mkdir build
 cd build
 cmake xxxx",
it doesn not generate a Makefile in build directory.

**Comment by Wayne901** [comment]
![Snipaste_2024-02-24_20-31-09](https://github.com/GLVis/glvis/assets/52063692/841a9c1b-06ba-41f4-8c3b-6968190a6e37)
cd share/ && xxd -i logo.rgba > \

    logo.rgba.bin.cpp

lib/sdl_x11.cpp:27:10: fatal error: X11/extensions/XInput2.h: No such file or directory

   27 | #include <X11/extensions/XInput2.h>

      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

make: *** [lib/sdl_x11.o] Error 1

make: *** Waiting for unfinished jobs....

**Comment by Wayne901** [comment]
The error is
![Snipaste_2024-02-24_20-31-09](https://github.com/GLVis/glvis/assets/52063692/abd4126f-9321-49d8-8321-08be677176c3)

**Comment by v-dobrev** [comment]
If you used CMake to build MFEM, you should use CMake to build GLVis too.

If you are on Ubuntu, try installing the package `libxi-dev` which contains the file `/usr/include/X11/extensions/XInput2.h`, see e.g. https://packages.ubuntu.com/mantic/amd64/libxi-dev/filelist.

If you are using a different distribution, try to find which package provides the missing file, `X11/extensions/XInput2.h`.

**Comment by Wayne901** [comment]
Thank you. Installing libXi-devel solved the problem.
