### ISSUE TITLE
Second order mesh, MFEM format vs VTK format

### ISSUE THREAD

**Issue by KazemKamran** [GLVis/glvis#29]
I have written a second order PUMI mesh to MFEM format then print it once using 'MFEM::Mesh::Print()' and once using 'MFEM::Mesh:PrintVTK()'. 

The VTK format loaded in Paraview shows a second order mesh as expected, however the MFEM format  loaded in glvis shows a linear mesh as you can see in the attached snapshots.  The MFEM format do have the nodes section required for the higher order meshes. 

![mfem_print](https://user-images.githubusercontent.com/22638666/28725906-04e41d06-738d-11e7-8376-09436f7500d5.png)
![mfem_print_vtk](https://user-images.githubusercontent.com/22638666/28725907-04e4cc6a-738d-11e7-88b8-fd9bc4275f51.png)

[MFEMformat.mesh.tar.gz](https://github.com/GLVis/glvis/files/1183613/MFEMformat.mesh.tar.gz)

**Comment by v-dobrev** [comment]
Press the 'o' key a few times to increase the sub-division factor. See [README](https://github.com/GLVis/glvis/blob/master/README) for more key commands, and the "3D data commands" section for some 3D specific keys.

**Comment by tzanio** [comment]
That's a really nice mesh @KazemKamran :)
