### ISSUE TITLE
Linking with shared libraries and RPATH

### ISSUE THREAD

**Issue by juan42** [GLVis/glvis#33]
Using the CMake build and linking with shared libraries doesn't produce consistent RPATH flags. 
```
ldd glvis 
	linux-vdso.so.1 =>  (0x00007ffff7d42000)
	libmfem.so => not found
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f61394c9000)
...
```
First, the project name has to be set before using FIND_* so global properties aren't overwritten. Refer
https://github.com/GLVis/glvis/blob/38dbcccaa565e28bd5ed8277a786b1af0e802ac0/CMakeLists.txt#L17

But that doesn't solve the RPATH issue with libmfem.so. Any ideas?

**Comment by v-dobrev** [comment]
@juan42,

I created a PR (#34) that fixed the issue for me. Can you try it on you computer and, if it works fine, approve the PR?

Thanks for reporting this issue!

**Comment by juan42** [comment]
This does not work for me. After
```
make install
```
i still don't have proper RPATH set in the installed binary. I have to configure with
```
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE
```
we can set this with
```
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
```
globally but i don't know enough about CMake if there is something wrong in another place since my projects link MFEM without problems (although kept and run in the build directory).

**Comment by v-dobrev** [comment]
OK, what I tested was just building MFEM (without installing it) and the just building GLVis pointing it to the MFEM build directory. Does this work for you?

I'll try now installing MFEM and then building / building+installing GLVis.

**Comment by juan42** [comment]
Just building GLVis without install works fine

**Comment by v-dobrev** [comment]
Even when linking to an installed version of MFEM?

**Comment by juan42** [comment]
Thats a good question. The CMake file from GLVis always picks up the folder which the build folder (i assume because they are in the same tree). But i think both worked.

**Comment by v-dobrev** [comment]
@juan42, I pushed some additions to the PR. Can you check if this solves the issue for you?

**Comment by juan42** [comment]
Perfect! Thanks @v-dobrev this works and even links all third party libraries which are configured with mfem to glvis.
