### ISSUE TITLE
CMAKE BINARY DIR 

### ISSUE THREAD

**Issue by stefanozampini** [GLVis/glvis#35]
@v-dobrev I'm not sure this is a problem on my Fedora 26 or a buggy CMakeLists.txt
This is the first time I'm trying an out-of-source cmake build of GLVis. For some reasons, ${CMAKE_SOURCE_DIR} and ${CMAKE_BINARY_DIR} are the same. Anyway, declaring the project before the check fixes the issue

```diff --git a/CMakeLists.txt b/CMakeLists.txt
index e33428a..7d5d334 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,5 +1,7 @@
 cmake_minimum_required(VERSION 2.8.12)
 
+project(glvis)
+
 # Prohibit in-source builds
 if ("${CMAKE_SOURCE_DIR}" STREQUAL "${CMAKE_BINARY_DIR}")
   message(FATAL_ERROR "In-source builds are prohibited.")
@@ -14,7 +16,6 @@ if (NOT CMAKE_CXX_COMPILER AND MFEM_CXX_COMPILER)
   set(CMAKE_CXX_COMPILER "${MFEM_CXX_COMPILER}")
 endif()
 
-project(glvis)
 
 # Default options match the Makefile
 if (NOT CMAKE_BUILD_TYPE)
```

**Comment by dalcinl** [comment]
Maybe `project(GLVis CXX)` ?

**Comment by stefanozampini** [comment]
Wait, it did not fix the problem. Anyway, the out-of-source CMAKE build of MFEM is fine. I HATE CMAKE

**Comment by juan42** [comment]
I dont think the in-source build has worked before?

**Comment by stefanozampini** [comment]
I'm not trying to do an in-source build. 
This does not work for me, I don't know why
$ mkdir build && cd build && cmake ..

**Comment by stefanozampini** [comment]
Forget about it, I fixed the issue. I had a CMakeCache.txt file in my source dir

**Comment by dalcinl** [comment]
@stefanozampini We'll never forget...
