### ISSUE TITLE
Understanding the Mesh NURBS format

### ISSUE THREAD

**Issue by vryy** [GLVis/glvis#37]
Hello

I have trouble understanding the NURBS mesh format used in Glvis. If I understood it correctly, each element represents a patch and each edge represents a patch boundary. The vertices of the element are the patch corners. The inner control points indexing are not described. Therefore I'm not clear how the control points in the FiniteElementSpace section relate to the patch. In the other way around, I do not know which control points the element shall own. Anyone can give a hint?

**Comment by v-dobrev** [comment]
Hi,

It is probably easier to use the alternative NURBS format, where NURBS-patches are described independently: up to and including the `vertices` the format is the same as described here: http://mfem.org/mesh-formats/#nurbs-meshes. After that, the alternative is the following:
```
...

vertices
<number of vertices>

patches

<patch 1>

...

<patch n>
```
where `n` is the number of elements as given in the `elements` section. The `<patch k>` section itself has the following structure:
```
knotvectors
3
4 5 0 0 0 0 0 1 1 1 1 1
4 5 0 0 0 0 0 1 1 1 1 1
4 5 0 0 0 0 0 1 1 1 1 1

dimension
3

controlpoints
<x coord> <y coord> <z coord> <w coord>
...
```
where the control points are given as homogeneous coordinates in Cartesian ordering. There is also another way of specifying the control points - it is fairly straightforward to follow the code in the [MFEM repository](https://github.com/mfem/mfem/blob/a9792d2f069cee73c2c5c4bd7020261bb6a943bd/mesh/nurbs.cpp#L321).

Hope this helps,
Veselin

**Comment by vryy** [comment]
Unfortunately, that doesn't help. What I want to know is that with a control point in the list, which patch it belongs to. I guess there is something to do with grid function. The way Mfem enumerates the basis functions on patches is not clear in the documentation.

**Comment by vryy** [comment]
Hi

Looking in the disc-nurbs.mesh, it is not like you described. There are 5 patches there, but only one control points section is declared.

MFEM NURBS mesh v1.0

#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# SEGMENT     = 1
# SQUARE      = 3
# CUBE        = 5
#

dimension
2

elements
5
1 3 4 5 6 7
1 3 0 1 5 4
1 3 1 2 6 5
1 3 3 7 6 2
1 3 0 4 7 3

boundary
4
1 1 0 1
1 1 2 3
1 1 1 2
1 1 3 0

edges
12
0 0 1
0 4 5
0 7 6
0 3 2
1 1 2
1 5 6
1 4 7
1 0 3
2 0 4
2 1 5
2 2 6
2 3 7

vertices
8

knotvectors
3
2 3 0 0 0 1 1 1
2 3 0 0 0 1 1 1
2 3 0 0 0 1 1 1

weights
1 1 1 1 1 1 1 1

0.7071067811865475244
1
1
0.7071067811865475244

0.7071067811865475244
1
1
0.7071067811865475244

1
1
1
1

1
0.8535533905932737622
0.8535533905932737622
0.8535533905932737622
0.8535533905932737622

FiniteElementSpace
FiniteElementCollection: NURBS2
VDim: 2
Ordering: 1

-2 -2
2 -2
2 2
-2 2
-1 -1
1 -1
1 1
-1 1

0 -4
0 -1
0 1
0 4

4 0
1 0
-1 0
-4 0

-1.5 -1.5
1.5 -1.5
1.5 1.5
-1.5 1.5

0 0
0 -2.5
2.5 0
0 2.5
-2.5 0

**Comment by v-dobrev** [comment]
Hello,

Here is an example of the alternative format that describes the patches one by one. You are right - none of the meshes in the MFEM repository use this particular format. However, you should be able to view the example below in GLVis. Also, if you open this file with the mesh-explorer miniapp (available in mfem/miniapps/meshing) and save it, it will be saved in the format used by the sample NURBS meshes in mfem's data directory.

```ascii
MFEM NURBS mesh v1.0

#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# SEGMENT     = 1
# SQUARE      = 3
# CUBE        = 5
#

dimension
2

elements
3
1 3 0 1 2 3
1 3 1 4 5 2
1 3 3 2 5 6

boundary
6
1 1 0 1
1 1 1 4
2 1 4 5
2 1 5 6
3 1 6 3
3 1 3 0

edges
9
0 0 1
0 3 2
0 6 5
1 0 3
1 1 2
1 4 5
2 1 4
2 2 5
2 3 6

vertices
7

patches

# patch 1
knotvectors
2
2 3 0 0 0 1 1 1
2 3 0 0 0 1 1 1

dimension
2

controlpoints
0    0      1
0.25 0      1
0.5  0      1
0    0.25   1
0.25 0.25   1
0.5  0.25   1
0    0.5    1
0.25 0.5    1
0.5  0.5    1


# patch 2
knotvectors
2
2 3 0 0 0 1 1 1
2 3 0 0 0 1 1 1

dimension
2

controlpoints
0.5  0    1
0.75 0    1
1    0    1
0.5                    0.25                  1
0.71193976625564337806 0.3163417161825448859 0.96193976625564337806
0.92387953251128675613 0.3826834323650897717 0.92387953251128675613
0.5  0.5  1
0.6035533905932737622 0.6035533905932737622 1
0.7071067811865475244 0.7071067811865475244 1


# patch 3
knotvectors
2
2 3 0 0 0 1 1 1
2 3 0 0 0 1 1 1

dimension
2

controlpoints
0    0.5  1
0.25 0.5  1
0.5  0.5  1
0    0.75 1
0.3163417161825448859 0.71193976625564337806 0.96193976625564337806
0.6035533905932737622 0.6035533905932737622 1
0    1    1
0.3826834323650897717 0.92387953251128675613 0.92387953251128675613
0.7071067811865475244 0.7071067811865475244 1
```

**Comment by vryy** [comment]
Hello

I have tested and see that this mesh format is easier to understand and generate except the awkward element connectivity which must be clockwise 0-1-3-2. I assume that is to be backward compatible with standard isoparametric mesh format.

The remaining question is how to visualize the results. For that i made a simple mesh for a square.
[sample_v1_square.mesh.txt](https://github.com/GLVis/glvis/files/1486990/sample_v1_square.mesh.txt)

And the results file:
[sample_v1_square.sol.txt](https://github.com/GLVis/glvis/files/1486995/sample_v1_square.sol.txt)

I noticed that I can change the FiniteElementCollection to NURBS2, NURBS3 and got different visualization results. I thought it should use the same basis function defined on the NURBS. In this case it is linear. In addition, if p_u != p_v, what is the FiniteElementCollection shall we use?

**Comment by v-dobrev** [comment]
Hi @vryy,

When you set the order (degree) of the collection to be NURBS2 (or any order higher than the mesh order), the library creates new NURBS space of the required order (using unit weights) by degree-elevation of the original mesh knot vectors. That space has more degrees of freedom and therefore the library expects more numbers - if those values are missing from the file (as in the case, when you replace `NURBS1` with `NURBS2`), the read operation returns 0, I think, for those missing values.

If I understand your question correctly, the case "p_u != p_v" corresponds to different orders for different knot vectors - support for that case is a new addition to MFEM (see the `varnurbs-dev` branch and the corresponding pull request, https://github.com/mfem/mfem/pull/279) which is currently under review. You are welcome to try it, and provide feedback.

**Comment by tzanio** [comment]
Hi @vryy, were you able to resolve this?

**Comment by vryy** [comment]
@tzanio I did not find time to try the MFEM branch for variable degree yet. I will do that within next week and report the results.

**Comment by tzanio** [comment]
Hi @vryy, we are planning to merge the [varnurbs-dev](https://github.com/mfem/mfem/pull/279) branch soon, so if you get a chance to try it and provide any feedback that will be most appreciated. Thanks!

**Comment by tzanio** [comment]
I'm closing this issue now. The variable order NURBS are now merged in MFEM's master. Feel free to reopen if you have further questions.

**Comment by vryy** [comment]
Hi @tzanio 

I believe the varnurbs works. The file below has different order in dimension and displays as expected

```
MFEM NURBS mesh v1.0

#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# SEGMENT     = 1
# SQUARE      = 3
# CUBE        = 5
#

dimension
2

elements
1
1 3 0 1 3 2

boundary
4
1 1 0 1
1 1 0 2
1 1 1 3
1 1 2 3


edges
4
0 0 1
1 0 2
1 1 3
0 2 3


vertices
4

patches

# patch 1

knotvectors
2
3 4 0 0 0 0 1 1 1 1
2 3 0 0 0 1 1 1

dimension
2

controlpoints
 200 1.4210854715202e-14 1
 160.947570824873 94.2809041582063 0.804737854124365
 94.2809041582063 160.947570824873 0.804737854124365
 4.2632564145606e-14 200 1
 150 1.06581410364015e-14 1
 120.710678118655 70.7106781186547 0.804737854124365
 70.7106781186547 120.710678118655 0.804737854124365
 3.19744231092045e-14 150 1
 100 7.105427357601e-15 1
 80.4737854124365 47.1404520791032 0.804737854124365
 47.1404520791032 80.4737854124365 0.804737854124365
 2.1316282072803e-14 100 1

```

On the results, the format shall be:

```
FiniteElementSpace
FiniteElementCollection: NURBS1
VDim: 1
Ordering: 1

value_at_control_point_1
value_at_control_point_2
...
```
If FiniteElementCollection==NURBS1 the default order will be used, for FiniteElementCollection==NURBS2 the order will be increased in both u&v, and so on?

**Comment by tzanio** [comment]
@IdoAkkerman, can you comment on @vryy's question above regarding variable order NURBS grid functions?

**Comment by vryy** [comment]
Hello, can anyone comment on this, so that I can really close this issue?

**Comment by v-dobrev** [comment]
Hi @vryy,

If I understand your question correctly, you want to know what the format for scalar variable-order NURBS solutions (i.e. `mfem::GridFunction`s) is. Is that correct?

If that is the case, here is what the solution file should look like (this example describes the solution by patches):
```ascii
FiniteElementSpace
FiniteElementCollection: NURBS
VDim: 1
Ordering: 1

NURBS_patches

<value_at_control_point_1__patch_1>
<value_at_control_point_2__patch_1>
...
<value_at_control_point_1__patch_2>
<value_at_control_point_2__patch_2>
...
```
Note that this example assumes the solution uses the same orders as the mesh.

Let me know if you encounter any issues with the above format.

**Comment by vryy** [comment]
@v-dobrev thanks for your info. I did as above with an example. Here I attached a mesh file, and the 2 result files. One for displacement field with 3 components, and the other for stress with 6 components.

[internal_pressurized_cylinder.zip](https://github.com/GLVis/glvis/files/3095126/internal_pressurized_cylinder.zip)

Glvis works and visualizes the displacement but i'm not sure if it reads correctly. Because the mesh should deform in the same plane. Can you modify the grid function file to the correct form? If this works, I would like to contribute this as an example.
