### ISSUE TITLE
Obscure error for periodic meshes without boundary attributes

### ISSUE THREAD

**Issue by stefanozampini** [GLVis/glvis#40]
If you don't specify the boundary attributes in 3D, and MFEM cannot compute automatically the boundary mesh (like in a fully periodic cube) , then GLVis errors out with a very obscure message for the user (this is because Array::Max() cannot be called)
 
https://github.com/GLVis/glvis/blob/7224f8646347a157428ecd554f81c2bf4700612b/lib/vssolution3d.cpp#L600

What should be the proper fix for this? I see that the rest of the code for the 3D visualization makes heavy use of the boundary mesh, and I don't see any simple fix except aborting at line 600 with a nice error message like "you need to specify the boundary attributes". Thoughts?

**Comment by v-dobrev** [comment]
I suggest the following resolution:
1) In the case when `mesh->Dimension() == 3`: if `mesh->bdr_attributes.Size() == 0`, then issue a warning (on the terminal) and set the size of `bdr_attr_to_show` to zero. This way there should be no crash, initially the plot will be empty but some of the features will still work, e.g. the cutting plane.
2) In the case of a surface mesh, i.e. `mesh->Dimension() != 3`: if `mesh->attributes.Size() == 0` then (in this case there are no elements in the mesh) we can issue a warning and set the size of `bdr_attr_to_show` to zero. Nothing will be visualized but that is fine for an empty mesh.

**Comment by stefanozampini** [comment]
Closing this issue, see https://github.com/GLVis/glvis/pull/41
