### ISSUE TITLE
Problems on building glvis

### ISSUE THREAD

**Issue by yuwenli925** [GLVis/glvis#44]
I am new to Linux. I use ubuntu on a virtualbox. Following the procedure on mfem.org, I can build and mfem-3.3.2 and run examples in it without problems. But when I was building glvis following exactly the procedure on mfem.org, I keep having troubles, both for glvis 3.3 applied to mfem3.3.2 and glvis 3.0 applied to mfem-3.0.  Please see the pictures.
![screenshot from 2017-12-17 02-37-11](https://user-images.githubusercontent.com/34620862/34078744-226110e8-e2d5-11e7-89a7-7878c0ab091c.png)
![screenshot from 2017-12-17 02-37-37](https://user-images.githubusercontent.com/34620862/34078745-2334de82-e2d5-11e7-90a8-ea1beb93a464.png)

**Comment by juan42** [comment]
You need to install the ubuntu package `mesa-common-dev` for example.

**Comment by yuwenli925** [comment]
Thank you very much for prompt reply. So I installed several packages about OpenGL like freeglut3, libglew-dev,  binutils-gold, mesa-common-dve. Now there is only one error. Do I need to install some other packages?
![screenshot from 2017-12-17 10-46-45](https://user-images.githubusercontent.com/34620862/34082736-71b97bf6-e318-11e7-9e56-e2566f7a7b8c.png)

**Comment by juan42** [comment]
Yes, this specific one is libpng12-dev. You can search https://packages.ubuntu.com/search?mode=filename&suite=precise&section=all&arch=any&keywords=png.h&searchon=contents here for specific files that you get as "missing file errors" and see which package you need to install.

**Comment by yuwenli925** [comment]
Thank you Juan. Now there is another error which I think is not "missing file error".  The compiler says fontconfig/fontconfig.h no such file or directory. But when I enter sudo apt-get install fontconfig, I found fontconfig already exists. I search on google for this error but there seems to be no simple solution.
![screenshot from 2017-12-17 11-36-39](https://user-images.githubusercontent.com/34620862/34083074-1a90f1b8-e31f-11e7-8b28-39e57f8b781c.png)

**Comment by juan42** [comment]
Yes. Fontconfig is installed but not the development package.

Install libfontconfig1-dev

**Comment by tzanio** [comment]
Thanks for answering this Julian!
