### ISSUE TITLE
CMake LibPNG define

### ISSUE THREAD

**Issue by gelever** [GLVis/glvis#45]
Hi,
I compiled GLVis with CMake and noticed screenshots weren't following the build parameters.

In the cmake file https://github.com/GLVis/glvis/blob/master/CMakeLists.txt#L160
The define for libpng should read 
```
 list(APPEND _glvis_compile_defs "GLVIS_USE_LIBPNG")
```

where `GLVIS_USE_PNG` -> ```GLVIS_USE_LIBPNG```

Thanks

**Comment by tzanio** [comment]
Good catch. Can you propose a PR?
