### ISSUE TITLE
XIO error

### ISSUE THREAD

**Issue by CsatiZoltan** [GLVis/glvis#47]
`glvis-3.3` nicely works, but after quitting, the following appears in the terminal:

```
XIO:   fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
       after 2822 requests (2822 known processed) with 0 events remaining.
```
It doesn't seem to have any effect on my workflow, but still wondering what causes it.

**Comment by tzanio** [comment]
I haven't seen this myself, but a quick web search points to an issue with one of the X libraries:

https://forums.ni.com/t5/LabWindows-CVI/XIO-fatal-IO-error-11/m-p/3183174#M71429

They suggest downgrading `libxcb`. Can you give this a try?

**Comment by CsatiZoltan** [comment]
I downgraded libxcb from 1.15 to 1.11, and it didn't help. Anyway, this is a non-blocking issue, the program still works flawlessly.
