### ISSUE TITLE
Plotting cut finite elements

### ISSUE THREAD

**Issue by CsatiZoltan** [GLVis/glvis#48]
The [CutFEM](http://onlinelibrary.wiley.com/doi/10.1002/nme.4823/abstract) method is easy to implement to existing FE softwares and enables the representation of discontinuities *within* an element. It is done by restricting the FE basis functions on a cut part of the element.

My question is the following: is it possible in GLVis to plot the mesh or a solution field only on part of a finite element? Example: consider a Q4 element cut by a straight discontinuity into two parts: a triangle and a pentagon. The plot on the pentagon/triangle can be easily created by interpolating the calculated nodal FE values to the vertices of the pentagon/triangle.

**Comment by tzanio** [comment]
This functionality will have to go into MFEM. We will be certainly interested in it, though I don't think it will be so simple to implement :)

That being said, I am not clear what your question is -- are you asking what you can do with the current capabilities, or commenting on what will be possible with such XFEM-like extension.

**Comment by CsatiZoltan** [comment]
My intention was both. But my question is: is this kind of plotting possible with the current version of GLVis?

**Comment by tzanio** [comment]
This is a pretty special case, but you can do something like this:

![glvis_s03](https://user-images.githubusercontent.com/1278247/35475153-1fa2b0fc-034e-11e8-9bd1-58bea26b9d07.png)

![glvis_s02](https://user-images.githubusercontent.com/1278247/35475152-1f8622c0-034e-11e8-937e-91f8157ec64d.png)

The above is the solution from ex1 of order 4 on a single element. Use `w` to cut the element and `x`, `y` and `z` to adjust the cutting line.

You can do the same in 3D cutting with `i` instead of `w` (the cutting plane has several modes in this case).

You cannot plot functions that are discontinuous in a single element.

**Comment by CsatiZoltan** [comment]
Thank you, I tried it. This is not exactly what I would like because

- I set the cutting plane on the displayed result. I already have a solution field which would need to be plotted.
- I face situations when more than one discontinuity cuts an element.

> You cannot plot functions that are discontinuous in a single element.

In fact, I would only have to plot a *continuous* function on a *part* of the element (this is one reason why the CutFEM is easier to implement than the standard enrichment-based X-FEM).
Do you know when (if ever) this kind of functionality will be available in GLVis (not in MFEM, I already have a code which solves the PDE in this ways, I would just need the visualization, because MATLAB is slow in plotting many elements)?

**Comment by tzanio** [comment]
Can you represent each of the "cuts" as union of triangles (or quads)? That will be the most straightforward way to use the current version of GLVis, but will require additional processing on your end. The triangles can be curved, and the continuous function on them can be high order. You can assign a common attribute to the triangles in each "cut" to keep them separate.

Another option could be to visualize "point cloud" data which we are thinking of adding following the work in the [tracer-dev](https://github.com/mfem/mfem/tree/tracer-dev) branch of MFEM.

Anything else, seems to me, will require that each element has a knowledge of the interfaces that intersect it. If you know equations for these, you could conceivably modify the refinement sampling algorithm not to include sub-elements that cross the interfaces.

@v-dobrev, @kennyweiss or some of our @GLVis/everyone users may have further suggestions.

**Comment by CsatiZoltan** [comment]
> Can you represent each of the "cuts" as union of triangles (or quads)?

Yes, because the domain integral is calculated by triangulating the cut element part, therefore I have that information. For the sake of visualization, I created a conforming mesh with doubled nodes to be able to represent the discontinuous function:
```
MFEM mesh v1.0

dimension
2

elements
4
1 2 0 1 2
2 2 3 6 7
2 2 6 3 4
2 2 5 6 4

boundary
6
1 1 0 1
2 1 4 5
2 1 5 6
2 1 6 7
2 1 7 3
1 1 2 0

vertices
8
2
0 0
0.5 0
0 0.5
0 0.5
0.5 0
1 0
1 1
0 1
```

It is displayed as follows:
![mesh](https://user-images.githubusercontent.com/12742890/35519833-a10341a2-0515-11e8-814c-745f047f207f.PNG)
The following messages are printed to the terminal:
```
Generating coloring starting with element 1 / 4
Number of colors: 2

The requested multisample mode is not available. Multisampling disabled.

Subdivision factors = 16, 1
Shading type : non-conforming (with subdivision)
```

> You can assign a common attribute to the triangles in each "cut" to keep them separate.

As you can see from my mesh file, I did it. But still, it doesn't elevate those elements I requested (in fact the elevated element changes from run-to-run).

A discontinuous solution can be plotted in this way:

```
FiniteElementSpace
FiniteElementCollection: Linear
VDim: 1
Ordering: 0

0
1
1
2
2
3
5
3

```
It results:
![glvis_s01](https://user-images.githubusercontent.com/12742890/35521329-c0deb822-0519-11e8-9bac-94639d87950b.png)
 Is there a way to perfectly remove the gap between the plotted elements (F3/F4 controls it in steps and as you can see there is either some small gap or some overlapping)?

**Comment by tzanio** [comment]
> Is there a way to perfectly remove the gap between the plotted elements (F3/F4 controls it in steps and as you can see there is either some small gap or some overlapping)?

This is due to a recent bug that should now be fixed. Can you pull mfem and rebuild?

> I created a conforming mesh with doubled nodes to be able to represent the discontinuous function

That's one approach, but in general doubling is not necessary -- we support discontinuous functions.

> As you can see from my mesh file, I did it. But still, it doesn't elevate those elements I requested (in fact the elevated element changes from run-to-run).

Meshes without solutions are plotted with a "checkerboard" function. Use the Mesh Explorer miniapp in mfem/miniapps/meshing to visualize the sub-domains with same attribute (materials option).

> A discontinuous solution can be plotted in this way:

Another approach is not to double any mesh nodes and use a grid function in from "L2-conforming" space (P1 means first order)

```
FiniteElementSpace
FiniteElementCollection: L2_T1_1D_P1
VDim: 1
Ordering: 1
...
```

**Comment by CsatiZoltan** [comment]
> This is due to a recent bug that should now be fixed. Can you pull mfem and rebuild?

After pulling the master branch from both mfem and GLVis, it works perfectly!

> Another approach is not to double any mesh nodes and use a grid function in from "L2-conforming" space (P1 means first order)
```
FiniteElementSpace
FiniteElementCollection: L2_T1_1D_P1
VDim: 1
Ordering: 1
...

```

It results a segfault (core dumped), without printing any other error messages.

> Meshes without solutions are plotted with a "checkerboard" function. Use the Mesh Explorer miniapp in mfem/miniapps/meshing to visualize the sub-domains with same attribute (materials option).

Calling `mesh-explorer` with `--mesh myMesh.mesh` recognizes the mesh and provides the data, but when I want to plot it, its drops the error `Unable to connect to localhost:19916`.

**Comment by tzanio** [comment]
> It results a segfault (core dumped), without printing any other error messages.

Try the following mesh:

```
MFEM mesh v1.0

dimension
2

elements
4
1 2 0 1 2
2 2 2 4 5
2 2 4 2 1
2 2 3 4 1

boundary
6
1 1 0 1
2 1 1 3
2 1 3 4
2 1 4 5
2 1 5 2
1 1 2 0

vertices
6
2
0 0
0.5 0
0 0.5
1 0
1 1
0 1
```

and grid function:

```
FiniteElementSpace
FiniteElementCollection: L2_T1_2D_P1
VDim: 1
Ordering: 1

0
0
0
0.5
2
1
2
0.5
0.5
1
2
0.5
```

**Comment by CsatiZoltan** [comment]
Both works now. Thanks.

**Comment by tzanio** [comment]
You are welcome. Let us know if you have any further questions.
