### ISSUE TITLE
GLvis doesn't build against an out-of-source MFEM build 

### ISSUE THREAD

**Issue by markcmiller86** [GLVis/glvis#50]
I tried building glvis-3.3 against an MFEM build that was "out-of-source" and it doesn't work. GLvis is looking for `config.mk` in `$(MFEM_DIR)/config`. If I specify `MFEM_DIR=../mfem/build` (which is where the built `libmfem.a` and `mfem.hpp` files are), the glvis make fails looking for `config.mk`

**Comment by tzanio** [comment]
This worked for me on my Mac:
```
git clone git@github.com:mfem/mfem.git
git clone git@github.com:glvis/glvis.git
cd mfem
make BUILD_DIR=build serial
cd ../glvis
make MFEM_DIR=../mfem/build
```
Can you post the commands that you are using?

**Comment by markcmiller86** [comment]
Ah, ok. I did *not* do make BUILD_DIR=..., I simply did this...

```
git clone git@github.com:mfem/mfem.git
cd mfem
mkdir build
cd build
cmake -D... ..
```

That actually builds everything fine. But, it doesn't make a config.mk file there ;)

**Comment by tzanio** [comment]
You can't mix them for now :), see https://github.com/mfem/mfem/issues/312

You can either use `make` (with MFEM build in- or out-of-source) for both MFEM and GLVis, or `CMake` for both of them.

In particular the following should work with a CMake build of MFEM:
```
cd glvis
mkdir build; cd build
cmake -D MFEM_DIR=../../mfem/build ..
```

**Comment by markcmiller86** [comment]
So, I am not seeing a CMakeListst.txt file in glvis-3.3

```
[scratlantis:~/fastmath/atpesc17_examples/mfem] miller86% ls glvis-3.3.tar.gz 
glvis-3.3.tar.gz
[scratlantis:~/fastmath/atpesc17_examples/mfem] miller86% gunzip < glvis-3.3.tar.gz | tar tf - | grep -i cmake
```

**Comment by tzanio** [comment]
Good point -- that was added in 879621285ddbbe0d, sorry!

You can either switch to master, instead of 3.3, or use the plain `make` build system.
