### ISSUE TITLE
Bad keystrokes result in runaway glvis windows crashing X server

### ISSUE THREAD

**Issue by markcmiller86** [GLVis/glvis#54]
Unfortunately, I can't recall exact key strokes that caused this. However, in a terminal window I am running mesh-explorer and I have a glvis process running as well moving back and forth between terminal window and glvis window to enter key strokes and change things. On more than a few occasions now, I've accidentally hit the wrong key in the wrong window causing mesh-explorer to loop endlessly...

```
S) Save
--> Generating coloring starting with element 7 / 8
Number of colors: 2

What would you like to do?
q) Quit
r) Refine
c) Change curvature
s) Scale
t) Transform
j) Jitter
v) View
m) View materials
b) View boundary
e) View elements
h) View element sizes, h
k) View element ratios, kappa
x) Print sub-element stats
f) Find physical point in reference space
p) Generate a partitioning
S) Save
--> Generating coloring starting with element 7 / 8
Number of colors: 2

What would you like to do?
q) Quit
r) Refine
c) Change curvature
s) Scale
t) Transform
j) Jitter
v) View
m) View materials
b) View boundary
e) View elements
h) View element sizes, h
k) View element ratios, kappa
x) Print sub-element stats
f) Find physical point in reference space
p) Generate a partitioning
S) Save
--> Generating coloring starting with element 7 / 8
Number of colors: 2

What would you like to do?
q) Quit
r) Refine
c) Change curvature
s) Scale
t) Transform
j) Jitter
v) View
m) View materials
b) View boundary
e) View elements
h) View element sizes, h
k) View element ratios, kappa
x) Print sub-element stats
f) Find physical point in reference space
p) Generate a partitioning
```

and worse, upon each iteration, it generates a new glvis window. If I catch it and bring things under control soon enough, I think all I wind up having to do is kill glvis and restart it manually. However, it can also sometimes crash my X server.

This is happening on OSX 10.11 with glvis-3.3 and mfem (master).

**Comment by v-dobrev** [comment]
Hi Mark,

The only explanation I can think of is the following: from the output you pasted above, it looks like the variable `mk` that is read from `cin` is set to `'e'` and then somehow consequent reads from `cin` (in the expression `cin >> mk;`) fail without changing the value of `mk` and this leads to the infinite loop which executes the `'e'` command every time resulting in opening a new window. I'm not sure how, in your case, the reading from `cin` fails but I don't see another explanation at the moment. One way this can happen is if `cin` is redirected from a file or a pipe and the last character in the file is `'e'` - we can add a gurad for that by checking `cin.good()` before reading.

I'll make a PR to add the check for `cin.good()`. If you have any other ideas what to change, let us know.
