### ISSUE TITLE
Too many open files when reading parallel mesh & solution

### ISSUE THREAD

**Issue by jakubcerveny** [GLVis/glvis#55]
After some recent changes in GLVis (meshes and solutions in the same file), it is no longer able to open a larger parallel solution (like 4096 CPUs). The error you get is something like

```Can not open mesh file: sedov_500_mesh.001013!```

while the file clearly exists and can be opened. It turns out GLVis is trying to open all of the files at once and the default limit on Ubuntu is ~1000 concurrently open files per process. The workaround is to increase the limit with something like `ulimit -n 10000`, but I think it shouldn't be necessary to keep all the files open and that we should eventually fix this.

**Comment by dylan-copeland** [comment]
I also have this problem, except I am using a machine where I am unable to use the workaround "ulimit -n 10000". A real fix is needed.

**Comment by tzanio** [comment]
@dylan-copeland and @jakubcerveny -- can this be simply addressed by opening the files one at a time?

**Comment by dylan-copeland** [comment]
@tzanio I don't know for sure, but that seems like a plausible solution worth trying.

**Comment by jakubcerveny** [comment]
I think it used to work before some changes (mesh+solution in the same file?), so it must be possible...

**Comment by tzanio** [comment]
Can you try deleting the closing the mesh files by deleting `meshfiles[p]` at the end of this loop: https://github.com/GLVis/glvis/blob/master/glvis.cpp#L1951-L1980 as opposed to the end of `ReadParMeshAndGridFunction`?

**Comment by jakubcerveny** [comment]
I think that would break loading the solutions later in the function. We could try fusing the two for cycles though...

**Comment by jakubcerveny** [comment]
Actually, that won't work either because the Mesh object needs to be created before any GridFunctions. I think the only solution is to close each mesh file in the first cycle, noting however the position in the file, in case the solution will need to be read from the same file later. If that is the case, the file can be reopened in the second for cycle and seeked to the stored position.

**Comment by jakubcerveny** [comment]
I wanted to draft a quick pull request when I realized one can't easily seek in an `ifgzstream` :-(  I'll think more about this...

**Comment by jakubcerveny** [comment]
On a second look, I think I was wrong in assuming the two cycles cannot be fused. The combined `mesh_p` and `sol_p` can both be created at the end. I'll look into this tomorrow...

**Comment by jakubcerveny** [comment]
I pushed a fix to `too-many-open-files-fix` but didn't test it too much, does it work for you @dylan-copeland?

**Comment by dylan-copeland** [comment]
@jakubcerveny Yes, your branch fixes the issue for me! Even on my MacBook (which got its heart-rate up) I was able to visualize a large solution with 1728 files, which fails with the master branch of glvis. Thanks for fixing this!

**Comment by tzanio** [comment]
Thanks @jakubcerveny !
