### ISSUE TITLE
Interest in MATLAB wrapper?

### ISSUE THREAD

**Issue by CsatiZoltan** [GLVis/glvis#59]
I am currently working on a simplistic MATLAB wrapper of GLVis. Originally, I intended to create a repo for it on my account. However, if this organization is interested in it, I could create the repository inside the [GLVis organization](https://github.com/GLVis).

**Comment by tzanio** [comment]
Hi @CsatiZoltan,

Yes that will certainly be of interest.

One option is that you start the development in your account and then transfer the ownership of the repository to the GLVis organization. This is what we did with https://github.com/mfem/PyMFEM.

Another option is to create the repository directly inside the GLVis organization.

I'm OK with both options :).

Cheers,
Tzanio

**Comment by CsatiZoltan** [comment]
I start it with my account and when it's mature, I will reopen this issue to discuss if you want it or not to be transferred.
