### ISSUE TITLE
Modern OpenGL port

### ISSUE THREAD

**Issue by kanye-quest** [GLVis/glvis#61]
Hello, I am currently working on creating a Jupyter add-on that uses GlVis, by building the library with emscripten. In the process, I have been porting over some of the immediate-mode OpenGL to a modern OpenGL featureset.

So far I have implemented:
- Replacing the fixed-function lighting/matrix stack with shaders
- Using a texture atlas to render text
- Using SDL2 for window/input management instead of X11

I currently have a couple more call lists left to convert into VBOs, before the GlVis library can be built with emscripten and used.

I'd be interested in hearing your thoughts or suggestions!

**Comment by tzanio** [comment]
Welcome @kanye-quest!

Yes, we are definitely interested. Feel free to create a branch in the GLVis org and issue a PR when you are ready.

Tzanio

**Comment by tzanio** [comment]
BTW, we've been wanting to modernize GLVIs for a long time.

One effort in that direction is @jakubcerveny's  https://github.com/jakubcerveny/hogtess

**Comment by v-dobrev** [comment]
Sounds very interesting!

**Comment by tzanio** [comment]
Hi @kanye-quest, are you ready to create a branch to share some of this work?

**Comment by tzanio** [comment]
> Do you want me to move my fork into a branch in the original repo?

That will be preferable. Alternatively you can issue a PR from your work, and [give us write access to it](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/).

**Comment by tzanio** [comment]
This issue is superseded by https://github.com/GLVis/glvis/pull/66
