### ISSUE TITLE
About install on Ubuntu 2018.04 LTS

### ISSUE THREAD

**Issue by xfliu** [GLVis/glvis#62]
I tried to install the glvis on Ubuntu 2018.04 LTS, but failed with the following error.

> /usr/bin/x86_64-linux-gnu-ld: lib/libglvis.a(aux_vis.o): Symbol 'XGetWindowAttributes' is not defined
> //usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line

After searching on Google, I got the answer as follows.

https://askubuntu.com/questions/1035062/glvis-linker-error-undefined-reference-to-symbol-xgetwindowattributs

Hope that this will be helpful to people with the same problem.

**Comment by v-dobrev** [comment]
Thanks for reporting this issue. I made a PR to address it.
