### ISSUE TITLE
-lX11 and vtk unstructured problem

### ISSUE THREAD

**Issue by DennisRoddeman** [GLVis/glvis#69]
Hi,

1. comment: I need -lX11 to compile glvis on my linux mint tara,
2. question: When I do 'glvis -m test.vtk (with the attached test.vtk) I get the next, why?
[test.zip](https://github.com/GLVis/glvis/files/2378465/test.zip)

    MFEM abort: VTK mesh is not UNSTRUCTURED_GRID!
 ... in function: void mfem::Mesh::ReadVTKMesh(std::istream&, int&, int&)
 ... at line 387 of file: mesh/mesh_readers.cpp
  Aborted (core dumped)

**Comment by v-dobrev** [comment]
Hi @DennisRoddeman,

There is an empty line in your VTK file, between the lines containing `ASCII` and `DATASET UNSTRUCTURED_GRID` that MFEM does not expect. If you remove it, you'll be able to read the file in MFEM.

It will be easy to add one line in MFEM to skip any white-space between the expected strings - this is in the function: [Mesh::ReadVTKMesh](https://github.com/mfem/mfem/blob/bbac26bffe986f9f4d0cee480dcdd1924ce699d9/mesh/mesh_readers.cpp#L370-L389)

Note that MFEM only reads the mesh data from the file, so any field data in the file will not be displayed by GLVis.

**Comment by v-dobrev** [comment]
Regarding the `-lX11` flag: are you building the current master branch, or the release (v3.4) version? If you are using the release version, can you try the master branch - I think the issue may be resolved there.

**Comment by DennisRoddeman** [comment]
Hi Veselin,

-lX11:  I think that I indeed took the release 3.4
VTK file: I will skip that line
only mesh: Ah, I didn't realise that, just started without reading manuals, I now wil read ... 

Thank you, Dennis
