### ISSUE TITLE
X Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by ben-s-southworth** [GLVis/glvis#76]
I am trying to visualize a mesh output from MFEM on Quartz, but get a BadValue error from GLVIS:

```
../buildOptTOSS3/glvis-3.3/glvis -m last_run_problem.mesh 

       _/_/_/  _/      _/      _/  _/
    _/        _/      _/      _/        _/_/_/
   _/  _/_/  _/      _/      _/  _/  _/_/
  _/    _/  _/        _/  _/    _/      _/_/
   _/_/_/  _/_/_/_/    _/      _/  _/_/_/

Generating coloring starting with element 221 / 1024
Number of colors: 2
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  20
  Current serial number in output stream:  21
```
The -DGLVIS_GLX10 (as suggested in Issue 5) is already in my makefile. Any other tips here?

**Comment by tzanio** [comment]
Which version of XQuartz and macOS are you running?

**Comment by ben-s-southworth** [comment]
Last week I was running OS 10.12.6 and Xquartz 2.7.9. This weekend I upgraded to OS 10.14 and Xquartz 2.7.11, but got the same error.

**Comment by tzanio** [comment]
And you are still getting the error with a clean clone of `master` without the `-DGLVIS_GLX10` option?

**Comment by tzanio** [comment]
That's unlikely to make a difference, but can you start Xquartz manually before you run the `glvis -m ...` command?

**Comment by ben-s-southworth** [comment]
I logged out of quartz, opened Xquartz, and logged back into quartz. Then I reset hard to the master branch for glvis, added the -DGLVIS_GLX10 flag in the makefile (where it is commented out), and compiled. Sample line looks like:
`cd lib; /usr/tce/packages/mvapich2/mvapich2-2.2-intel-18.0.1/bin/mpicxx -O3 -DNDEBUG -I/g/g19/bs/quartz/mfem/bens_build -I/g/g19/bs/quartz/metis/build/Linux-x86_64/include -I/g/g19/bs/quartz/hypre/src/hypre/include -DGLVIS_MULTISAMPLE=4 -DGLVIS_MS_LINEWIDTH=1.4 -I/usr/include -DGLVIS_GLX10 -DGLVIS_USE_LIBPNG -DGLVIS_USE_FREETYPE -I/usr/include/freetype2 -c vsvector.cpp`

But, the error persists even on a simple attempt to visualize an MFEM mesh from the parent directory of MFEM and GLVIS:

```
quartz $ ./glvis/bin/glvis -m mfem/data/beam-hex.mesh 

       _/_/_/  _/      _/      _/  _/
    _/        _/      _/      _/        _/_/_/
   _/  _/_/  _/      _/      _/  _/  _/_/
  _/    _/  _/        _/  _/    _/      _/_/
   _/_/_/  _/_/_/_/    _/      _/  _/_/_/

Generating coloring starting with element 8 / 8
Number of colors: 2
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  20
  Current serial number in output stream:  21
```

**Comment by ben-s-southworth** [comment]
A new postdoc Ben Yee had a similar issue but was addressed by using an older version of Xquartz; would this help? I was running a fairly outdated version already last week though (2.7.9).

**Comment by v-dobrev** [comment]
Wait, are you trying to run GLVis remotely on a linux server and visualize it locally on a Mac?

**Comment by ben-s-southworth** [comment]
@v-dobrev Yes

**Comment by v-dobrev** [comment]
I just tried this on Mac (macOS 10.13.6 with XQuartz 2.7.11) and it worked fine. However, this is with an ssh connection that I just opened - I've had issues with the X connection going bad after some time - initially I can open X applications (emacs) fine but later it no longer works.

Can you try restarting your ssh connection? I know this is not a real solution but it is not a GLVis issue either.

**Comment by ben-s-southworth** [comment]
Strange, yea I have tried rebooting and starting a fresh ssh. How is your ssh set up? I have my ~/.ssh/config file set up like

```
host quartz
hostname quartz.llnl.gov
user my_username
ForwardX11 yes
ForwardX11Trusted yes
```

**Comment by v-dobrev** [comment]
I use `ssh -X quartz.llnl.gov`. Can you open other X applications, e.g. xterm?

**Comment by tzanio** [comment]
On my Macs (laptop and iMac with macOS 10.13.6) I have to use `-Y` instead of `-X`, but otherwise the following works both when I'm plugged in the network and via Wi-Fi:

```
ssh -Y quartz.llnl.gov
```

(Also, my ` ~/.ssh/config` files are essentially empty)

**Comment by tzanio** [comment]
Thanks Ben.

Acording to https://github.com/CDAT/vcdat/wiki/Troubleshooting, you need to reboot after the `default write` command. Did you try that?
