### ISSUE TITLE
fail compiling glvis-3.4 on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by vryy** [GLVis/glvis#81]
I have this error when compiling on Ubuntu 18.04 LTS

/usr/bin/ld: lib/libglvis.a(aux_vis.o): undefined reference to symbol 'XGetWindowAttributes'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line

This does not happen with glvis3.3, so I think this issue is recently introduced.

**Comment by tzanio** [comment]
Can you try the solution proposed in #79 (using latest master branches for both mfem and glvis)?

**Comment by vryy** [comment]
yes, it works. Thank you.
