### ISSUE TITLE
Setting min/max value does not work

### ISSUE THREAD

**Issue by najlkin** [GLVis/glvis#83]
The key F7 for setting min/max value does not work in server mode. I have tried to track it back and it is broken since the commit c05738f , which added the key combination Shift+F7 for setting the whole bounding box.

**Comment by tzanio** [comment]
Thanks for reporting this. I can reproduce it on Linux, though it seems to work fine on Mac.

Revising the `if` statement as follows seems to fix it:

```c++
void KeyF7Pressed(GLenum state)
{
   if (state & ShiftMask)
   {
      // Shift + F7 code
   }
   else
   {
      // F7 code
   }
}
```
@v-dobrev -- what do you think?

**Comment by v-dobrev** [comment]
Sounds good to me - make the change.

**Comment by tzanio** [comment]
@najlkin, can you confirm that #84 works for you?

**Comment by najlkin** [comment]
Yes, it works perfectly for me :wink: The issue was hardware specific maybe. I have tried master branch at a different computer with nearly the same OS and there were no problems at all. It seems that certain piece of hardware in combination with certain OS sets some extra stuff in the state variable, but there is no need to test all bits anyway.
