### ISSUE TITLE
Update repo topics

### ISSUE THREAD

**Issue by hauten** [GLVis/glvis#86]
A new page on the LLNL software portal (https://software.llnl.gov/radiuss/) will soon dynamically pull in RADIUSS repos. To achieve this, we need RADIUSS-related repos outside the LLNL org to be tagged with relevant topics. See LLNL/llnl.github.io#17, LLNL/llnl.github.io#151, & https://github.com/LLNL/llnl.github.io/blob/new-home-page/radiuss/README.md for additional context.

GLVis already has `data-viz`. Please also add `radiuss`.

**Comment by tzanio** [comment]
Done. Thanks @hauten!
