### ISSUE TITLE
GLVis build failed

### ISSUE THREAD

**Issue by RashikShahjahan** [GLVis/glvis#87]
I am trying to build GLVis using `make MFEM_DIR=../mfem-3.0 -j` however I am getting the following errors:
```

aux_vis.hpp:17:10: fatal error: GL/glx.h: No such file or directory
 #include <GL/glx.h>

openglvis.cpp: In member function ‘void Camera::GLMultTransposeRotMatrix()’:
openglvis.cpp:100:4: error: ‘glMultTransposeMatrixd’ was not declared in this scope
    glMultTransposeMatrixd(mat);
```

**Comment by tzanio** [comment]
You need OpenGL support, either XQuarz on Mac or the corresponding Linux packages, see

https://github.com/GLVis/glvis/blob/master/INSTALL#L117-L120

**Comment by RashikShahjahan** [comment]
@tzanio I am using Cygwin on Windows 10.

**Comment by tzanio** [comment]
Then see https://github.com/GLVis/glvis/blob/master/INSTALL#L32-L34

**Comment by RashikShahjahan** [comment]
I am getting this now: lib/libglvis.a(tk.o):tk.cpp:(.text+0x2884): undefined reference to `XFreeFont'
 And bunch of similar errors.

**Comment by tzanio** [comment]
Try setting `GLVIS_USE_FREETYPE = NO` in the makefile
