### ISSUE TITLE
keys do not work reliably from command line

### ISSUE THREAD

**Issue by barker29** [GLVis/glvis#88]
If you run MFEM example 1 and then try to visualize the solution like so:
```
glvis -m refined.mesh -g sol.gf -k cS
```
The saved figure does not have the colorbar, as you would expect from the `c` key.

If you run it and enter the same keys by hand, the saved figure does have the colorbar.

I would like to use GLVis in scripts to automatically generate pictures with colorbars but so far am unable to do so.

**Comment by v-dobrev** [comment]
You should be able to use a GLVis script -- see https://glvis.org/options-and-use/#glvis-scripts.

The script commands are not documented but they are easy to see in this function:
https://github.com/GLVis/glvis/blob/20aeb2c03ce70f445232dba74179e03c94de0c2c/glvis.cpp#L641

**Comment by barker29** [comment]
Thanks for the response. 

My issue with GLVis scripts is they run interactively. Pressing the space bar (or any other keys) is exactly what I am trying to avoid.

In any case, this is a minor issue.

**Comment by v-dobrev** [comment]
You can generate the data for all screenshots and then create and run one GLVis script -- then you need to press space bar only once. Also, you can probably generate the GLVis script from your script.

That said, it is probably not too hard to update the way the `S` key is handled when given at the command line -- we just need to force an update of the GLVis window before we actually take the screenshot. Do you want me to try to add this?

**Comment by v-dobrev** [comment]
Looking at the code, it seems like you may be able to force a redraw before the `'S'` key is processed by adding the "key" `'~e'` -- e.g. `glvis -m refined.mesh -g sol.gf -k "c~eS"`. Can you try this?

**Comment by barker29** [comment]
Yes, the `~e` trick works fine. Thanks!
