### ISSUE TITLE
header files missing

### ISSUE THREAD

**Issue by bradfc** [GLVis/glvis#90]
I'm trying to build and install GLVis in conjunction with MFEM on an Odroid N2 - a 6-core SOC with ARM architecture.  I have built MFEM and built or installed freetype2 and fontconfig.  Nevertheless, I'm getting errors like this when I try to build GLVis:

ft2build.h not found
fontconfig.h not found

Since it has stalled at this point there may be other files not found.  I can try to locate these files by hand, but I wonder if I'm missing something in the installation sequence.

**Comment by v-dobrev** [comment]
Are you using GNU make to build GLVis? If that is the case, take a look at the following section of the makefile:
https://github.com/GLVis/glvis/blob/ab82359a9b8adb548369a9514c183703140bd7b2/makefile#L157-L170

You may need to set `FT_OPTS` manually, e.g. edit the `-I...` flag.

**Comment by bradfc** [comment]
I was able to do that for freetype2, but for fontconfig, the header file isn’t there, even though I installed the package using apt-get.  If I try uninstalling that with the intent to build from scratch, I get messages that emacs depends upon it.   I’m nervous about breaking dependencies just to get this to work.

**Comment by v-dobrev** [comment]
You probably need the development package for fontconfig which should include the header files -- it should have a name like `fontconfig-dev` or `fontconfig-devel`. I just looked and on ubuntu it looks like you want the package: `libfontconfig1-dev`, see e.g. https://packages.ubuntu.com/bionic/libfontconfig1-dev

**Comment by bradfc** [comment]
Thanks.  I did find the development packages and was able to complete the installation.  In the meantime, when I run GLVis with MFEM I get only gray-shade images as opposed to full color, though I do get color images when running GLVis in stand-alone mode (Issue #91).
