### ISSUE TITLE
Black & white image (no color) with MFEM

### ISSUE THREAD

**Issue by bradfc** [GLVis/glvis#91]
I managed to build MFEM and GLVis on an Odroid N2 - a 6-core SOC with ARM architecture. It runs Ubuntu with gcc and OpenMP installed. When I launch GLVis, I get the following:

Waiting for data on port 19916 ...
Window type not found!
Initializing the visualization failed.

Not sure what the problem is.  The Odroid is running headless, and I access it via tightvnc.  Could that be the problem?

**Comment by bradfc** [comment]
Addendum: I got that error to go away by building GLVis using

GL_OPTS = -lX11 -DGLVIS_GLX10

in the Makefile.

However, now when I run the first MFEM example:

ex1 -m ../data/star.mesh

I get a sketchy black and white outline rather than a full color image.  

I get a color image if I run GLVis on a sample mesh, but not if I run MFEM.

**Comment by tzanio** [comment]
Do you mean: "I get a color image if I run **MFEM** but not if I run **GLVis on a sample mesh**"?

If so, that's the intended behavior -- when visualizing a mesh without a solution, GLVis just shows a checkerboard coloring of the elements. So with `glvis -m star.mesh` you should see something like this:

![GLVis_s00](https://user-images.githubusercontent.com/1278247/69919804-a0b10780-1435-11ea-945f-3ff17d9a54a4.png)

Example 1 sends mesh+solution, so with `ex1 -m ../data/star.mesh` you should see:

![GLVis_s01](https://user-images.githubusercontent.com/1278247/69919795-8a0ab080-1435-11ea-9cb7-d1a8d8ea4e87.png)

Tzanio

**Comment by bradfc** [comment]
Actually, here's what I get if I run Example 1

![image](https://user-images.githubusercontent.com/26093496/69968316-29887b80-14e8-11ea-8897-d2c79cc3d744.png)

It's black & white with shading, no color.  For the first example, I do get the checkerboard pattern.

**Comment by tzanio** [comment]
Can you press `c` and `p` in the GLVis window? Do you get a different (colored palette)?

**Comment by bradfc** [comment]
If I press c, I get a vertical scale on the right-hand side of the window, but if I press p repeatedly I do get different color/shading combinations.  I didn't realize there were options.

**Comment by tzanio** [comment]
For some reason the default color palette on your machine is the white one... Can you post the MFEM code that sends the data to GLVis?

And yes, there are many "magic keys", see https://github.com/GLVis/glvis/blob/master/README :)

**Comment by bradfc** [comment]
The code is simply ex1.cpp, unedited, and run as suggested above.

The machine is an Odroid N2 (armhf architecture) running Ubuntu 18.04.

**Comment by tzanio** [comment]
I'm not sure what else can be going on here but one way to "fix" this is to send keys to the GLVis window as in:

https://github.com/mfem/mfem/blob/master/examples/ex10.cpp#L403

For example the keys could be `keys ppcm\n`.

**Comment by bradfc** [comment]
That should work - thanks!
