### ISSUE TITLE
GLVis does not work through XWin32, does through RealVNC

### ISSUE THREAD

**Issue by solberg2** [GLVis/glvis#93]
When I try to run GlVis through XWin32 back to a Windows machine, the visualization window pops up for just a second and then disappears.  Otherwise the command line is present, etc.   This does not happen through RealVNC, but there are other issues with using that.

**Comment by v-dobrev** [comment]
I have not tried running GLVis with XWin32. Some time ago I was able to build and run GLVis under cygwin -- see https://github.com/GLVis/glvis/issues/42#issuecomment-348492951 and the follow-up https://github.com/GLVis/glvis/issues/42#issuecomment-348681930.

I think you can also build and run GLVis using "Ubuntu bash shell (running as subsystem on Windows 10)" -- see #73.

**Comment by v-dobrev** [comment]
See also #79 for a related issue with "Windows Subsystem Linux Ubuntu 18.04".

**Comment by solberg2** [comment]
I'm not trying to build it under XWin32 (that's not possible).  I'm just trying to send the graphics back, like other XWindows applications do.  I have a workaround, but it seems like something is not correct here.

**Comment by v-dobrev** [comment]
Oh, are you running GLVis on a remote machine using XWin32 as the X-server?

One thing you can try is to un-comment the second line here:
https://github.com/GLVis/glvis/blob/ab82359a9b8adb548369a9514c183703140bd7b2/makefile#L135-L136

This helps with some X-servers.

**Comment by solberg2** [comment]
Yes, that is what I am trying to do.  Thank you so much for helping!  That didn't work.  I am investigating some more.  Thanks so much again

**Comment by tzanio** [comment]
@solberg2, were you able to find more?

**Comment by solberg2** [comment]
Never could get it to work.  Finally gave up.

**Comment by tzanio** [comment]
Ok thanks. If you can use RealVNC, I think that's preferable anyway...
