### ISSUE TITLE
Visualize multiple meshes

### ISSUE THREAD

**Issue by kmittal2** [GLVis/glvis#94]
I would like to overlay two meshes in the same GLVis window for comparison purposes. What is the best way to do this in GLVis?

**Comment by v-dobrev** [comment]
If your meshes have the same connectivity, you can send to GLVis one of the meshes and as a solution send the displacement to the other. This is what happens in `ex2`/`ex2p`. Then to see both meshes in GLVis press the following keys: `mdbe` -- in example 2 this will show the mesh (here this is the deformed configuration) in black and the mesh+displacement in red (here displacement is the backward displacement to the original un-deformed configuration). The same (or similar) should work for the `mesh-optimizer`/`pmesh-optimizer` miniapps.

**Comment by kmittal2** [comment]
Thanks @v-dobrev. I am trying to compare two different meshes with different connectivity (but for the same domain).

**Comment by kmittal2** [comment]
I am able to visualize two meshes simultaneously using Visit so I am closing this issue.
