### ISSUE TITLE
GLVis fails to build from spack

### ISSUE THREAD

**Issue by MPhysXDev** [GLVis/glvis#95]
We have been trying (unsuccessfully) to build GLVis with spack, see attached output:

[GLVis spack.txt](https://github.com/GLVis/glvis/files/3895989/GLVis.spack.txt)

Trying to further constrain the spec of virtual gl packages (spack install glvis ^mesa ^mesa-glu) does not change a thing.

Any idea ?

MPhysX Development Team

PS: there is nothing to be found in the spack-build-out.text file btw, except that spack entered the edit phase...

**Comment by tzanio** [comment]
@goxberry and @acfisher -- can you check this?

**Comment by v-dobrev** [comment]
Judging by the line
```console
==> Error: NoLibrariesError: Unable to recursively locate mesa libraries in /spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.4.0/mesa-18.3.6-fzp2hpf2dkdjtz44stu4jizpmkdpvxxv
```
I think this is an issue with the `mesa` spack package (https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mesa/package.py) -- it does not define the `libs` property (e.g. as in the `mesa-glu` package, https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mesa-glu/package.py) which is needed in the line highlighted by spack:
```console
  >>     88        gl_libs = spec['glu'].libs + spec['gl'].libs + spec['libx11'].libs
```
Specifically, I think the part `spec['gl'].libs` is the one that triggers the error.

You can try adding the `libs` property to the `mesa` package -- e.g. copy+paste the code from `mesa-glu` and replace `libGLU` with `libGL`. If this resolves the problem we can create a spack issue and suggest a resolution.

**Comment by samanseifi** [comment]
This worked for me. Thanks

**Comment by tyszwh** [comment]
This not work for me. When I add the code
`    def libs(self):
        for dir in ['lib64', 'lib']:
            libs = find_libraries('libGLU', join_path(self.prefix, dir),
                                  shared=True, recursive=False)
            if libs:
                return libs`
to the mesa/package.py. The mesa-glu can not install normally through spack

"Error: AttributeError: 'function' object has no attribute 'directories'

/home/spack/lib/spack/spack/build_environment.py:818, in child_process:
        815            tb_string = traceback.format_exc()
        816
        817            # build up some context from the offending package so we can
  >>    818            # show that, too.
        819            package_context = get_package_context(tb)
        820
        821            build_log = None


==> Error: Failed to install mesa-glu due to ChildError: AttributeError: 'function' object has no attribute 'directories'
/home/spack/lib/spack/spack/build_environment.py:818, in child_process:
        815            tb_string = traceback.format_exc()
        816
        817            # build up some context from the offending package so we can
  >>    818            # show that, too.
        819            package_context = get_package_context(tb)
        820
        821            build_log = None

"

**Comment by v-dobrev** [comment]
I created a PR in spack to fix this: https://github.com/spack/spack/pull/15716. Can you try that? Let me know if that does not work for you.

**Comment by v-dobrev** [comment]
The spack PR is now merged, so I'll close this issue.

**Comment by tyszwh** [comment]
That's works now. Thanks
