### ISSUE TITLE
How to add legend, labels inside a figure?

### ISSUE THREAD

**Issue by issabass** [GLVis/glvis#97]
Hello,
Team GLViS, maybe it is already there, but i do not see how to add labels, legend apart from colormap bar. How to add text, legend and alike to add more comments inside the figure?

When running example like custom case ex5/p5, i'd like to know how to plot vector-valued solutions (with rows not glyph) in its form [u1,u2] not its  magnitude?

Also, is possible to split the window plot into, say two subplots, to show for instance the exact and computed solution side by side not in two different plots?

Thank you much,
zaq

**Comment by tzanio** [comment]
Hi @issabass,

GLVis has limited customization options, if that's what you need you will be probably better off exporting the data to VisIt or ParaView and customizing there, see e.g. the example of such integration in Example 5.

That being said, you can customize the window title, and add a caption see e.g. https://github.com/mfem/mfem/blob/master/miniapps/tools/lor-transfer.cpp#L238-L241.

There is no way to split a window, but you can arrange windows next to each other, see again the LOR Transfer miniapp above.

Finally, you can switch the way a vector field is plotted with the `v` key. Several options are available, see https://github.com/GLVis/glvis/blob/master/README#L189-L196.

Hope this helps,
Tzanio
