### ISSUE TITLE
How to chose the level lines in a visualisation ?

### ISSUE THREAD

**Issue by LeilaSalomon** [GLVis/glvis#98]
Hello,

I would like to know how to chose level lines on a visualization.  When I use "m" on the visualization, I try "F5" to modify the level lines, but it doens't work...

I hope you could help me,

Best,
Leïla

**Comment by v-dobrev** [comment]
After pressing F5 in the GLVis window, switch to the terminal where you started `glvis` -- you should see a prompt: `Enter min : ` there. Just enter the min, max, and number of level lines there and then the GLVis window should be updated.

**Comment by LeilaSalomon** [comment]
> After pressing F5 in the GLVis window, switch to the terminal where you started `glvis` -- you should see a prompt: `Enter min : ` there. Just enter the min, max, and number of level lines there and then the GLVis window should be updated.

Thanks a lot for your reply ! 
Is it possible to have the mesh and the level lines on the same visualization ?

**Comment by tzanio** [comment]
> Is it possible to have the mesh and the level lines on the same visualization ?

No, not in GLVis.

**Comment by v-dobrev** [comment]
>  Is it possible to have the mesh and the level lines on the same visualization ?

It is not that difficult to edit the source to plot both. For example, for 2D scalar field, edit the lines:
https://github.com/GLVis/glvis/blob/ab82359a9b8adb548369a9514c183703140bd7b2/lib/vssolution.cpp#L2278-L2286

by replacing
```c++
    glCallList(lcurvelist);
```
with
```c++
    glCallList(linelist);
    glCallList(lcurvelist);
```

**Comment by LeilaSalomon** [comment]
> > Is it possible to have the mesh and the level lines on the same visualization ?
> 
> It is not that difficult to edit the source to plot both. For example, for 2D scalar field, edit the lines:
> https://github.com/GLVis/glvis/blob/ab82359a9b8adb548369a9514c183703140bd7b2/lib/vssolution.cpp#L2278-L2286
> 
> by replacing
> 
> ```c++
>     glCallList(lcurvelist);
> ```
> 
> with
> 
> ```c++
>     glCallList(linelist);
>     glCallList(lcurvelist);
> ```
Yes ! Thank you so much !!!
