### ISSUE TITLE
Inconsistency between key commands in 2D and 3D

### ISSUE THREAD

**Issue by rw-anderson** [GLVis/glvis#99]
key i: mesh subdivision in 2D, cutting plane toggle in 3D
key o: no-op in 2D, mesh subdivision in 3D

Proposal: move mesh subdivision function from 'i' to 'o' in 2D, leaving 'i' as no-op in 2D.

**Comment by tzanio** [comment]
I am OK with this proposal, as well as any other unification that will make things easier for users.

**Comment by rw-anderson** [comment]
Addressed in #126
